apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.28.1
        ports:
          - name: http-port
            containerPort: 8081
        volumeMounts:
          - name: nexus-vol
            mountPath: /var/nexus_vol
      volumes:
        - name: nexus-vol
          emptyDir: {}
