---

- name: "[KUBECTL] install for {{ linux_distribution }}"
  include_tasks: "kubectl_{{ linux_distribution }}.yml"
  tags:
    - kubectl

- name: "[KUBECTL] configure shell"
  block:
    - name: "[KUBECTL] check if .bashrc exists"
      stat:
        path: "{{ ansible_user_dir }}/.bashrc"
      register: bashrc_exists

    - name: "[KUBECTL] insert line in .bashrc"
      lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: "source <(kubectl completion bash)"
        state: present
      when: bashrc_exists.stat.exists

    - name: "[KUBECTL] check if .zshrc exists"
      stat:
        path: "{{ ansible_user_dir }}/.zshrc"
      register: zshrc_exists

    - name: "[KUBECTL] insert line in .zshrc"
      lineinfile:
        path: "{{ ansible_user_dir }}/.zshrc"
        line: "source <(kubectl completion bash)"
        state: present
      when: zshrc_exists.stat.exists
  become: false
  tags:
    - kubectl

- name: "[HELM] installation"
  import_tasks: helm.yml
  tags:
    - helm

- name: "[HETZNER_KUBE] installation"
  import_tasks: hetzner_kube.yml
  tags:
    - hetznerkube

- name: "[KOPS] installation"
  import_tasks: kops.yml
  tags:
    - kops

- name: "[LENS] installation"
  import_tasks: lens.yml
  tags:
    - lens

- name: "[KIND] installation"
  import_tasks: kind.yml
  tags:
    - kind

- name: "[MICROK8S] installation"
  import_tasks: microk8s.yml
  when: linux_distribution in ['ubuntu', 'debian']
  tags:
    - microk8s

- name: "[KOMPOSE] installation"
  import_tasks: kompose.yml
  tags:
    - kompose
