---

- include_tasks: "kubectl_{{ linux_distribution }}.yml"
  tags:
    - kubectl

- block:
    - name: "[KUBECTL] check if .bashrc exists"
      stat:
        path: "{{ ansible_user_dir }}/.bashrc"
      register: bashrc_exists

    - name: "[KUBECTL] insert line in .bashrc"
      lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: "source <(kubectl completion bash)"
        state: present
      when: bashrc_exists.stat.exists

    - name: "[KUBECTL] check if .zshrc exists"
      stat:
        path: "{{ ansible_user_dir }}/.zshrc"
      register: zshrc_exists

    - name: "[KUBECTL] insert line in .zshrc"
      lineinfile:
        path: "{{ ansible_user_dir }}/.zshrc"
        line: "source <(kubectl completion bash)"
        state: present
      when: zshrc_exists.stat.exists
  become: false
  tags:
    - kubectl

- import_tasks: helm.yml
  tags:
    - helm

- import_tasks: hetzner_kube.yml
  tags:
    - hetznerkube

- import_tasks: kops.yml
  tags:
    - kops

- import_tasks: lens.yml
  tags:
    - lens
