---

- name: "[KUBECTL] [FEDORA] copy file repository"
  copy:
    src: kubectl.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: "[KUBECTL] [FEDORA] install kubectl package"
  yum:
    name: kubectl
    state: latest
    update_cache: true
