---

- name: "[LENS] installation"
  when: linux_distribution != "ubuntu"
  block:
    - name: "[LENS] create {{ ansible_user_dir }}/AppImage directory"
      file:
        path: "{{ appimage_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: "[LENS] Get latest version of lens"
      uri:
        url: "{{ lens_latest_url }}"
        follow_redirects: safe
        body_format: raw
      register: lens_latest

    - name: "[LENS] download lens appimage"
      vars:
        lens_version: "{{ lens_latest.url | urlsplit('path') | basename }}"
      get_url:
        url: "https://github.com/lensapp/lens/releases/download/{{ lens_version }}/Lens-{{ lens_version[1:] }}.AppImage"
        dest: "{{ appimage_dir }}/Lens.AppImage"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: "[LENS] how to run"
      debug:
        msg: "Puedes ejecutar Lens con el comando: '{{ appimage_dir }}/Lens.AppImage'"

- name: "[LENS] ubuntu instalation"
  snap:
    name:
      - kontena-lens
    state: present
