---

- name: "[DOCKER] Create user config directory"
  file:
    path: "/home/{{ ansible_user }}/.docker"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "[DOCKER] Create config.json"
  copy:
    src: "docker.config.json"
    dest: "/home/{{ ansible_user }}/.docker/config.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: "[DOCKER] Create daemon.json"
  become: true
  become_method: sudo
  template:
    src: "daemon.json.j2"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: "[DOCKER] Restart docker"
  become: true
  become_method: sudo
  systemd:
    name: docker
    state: restarted
