---

- name: "include secrets file"
  include_vars:
    file: "secrets.yml"

- name: "Configure ssh"
  template:
    src: ssh_config.j2
    dest: "{{ ssh_user_dir }}/config"
    mode: 0600
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Create ssh keypair"
  openssh_keypair:
    path: "{{ ssh_user_dir }}/id_rsa"
    type: rsa
    size: 4096
    comment: "{{ ansible_user }}@{{ inventory_hostname }}"
    mode: 0600
    state: present
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Create ssh keys"
  block:
    - name: "Create subdirectories"
      file:
        path: "{{ ssh_user_dir }}/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - aws
        - ccr

    - name: "Generate files"
      copy:
        content: "{{ item.key }}"
        dest: "{{ ssh_user_dir }}/{{ item.file }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600
        remote_src: true
      loop: "{{ ssh_priv_keys }}"
      no_log: true
