---

- name: "[NETWORK] include secrets file"
  include_vars:
    file: "secrets.yml"

- name: "[NETWORK] Create openvpn directory"
  file:
    path: "{{ openvpn_user_dir }}/{{ item.name }}"
    state: directory
  loop: "{{ openvpn }}"
  no_log: true

- name: "[NETWORK] Copy p12 files"
  copy:
    src: "{{ item.name }}.p12"
    dest: "{{ openvpn_user_dir }}/{{ item.name }}/{{ item.name }}.p12"
    mode: 0600
  loop: "{{ openvpn }}"
  no_log: true

- name: "[NETWORK] Generate key files"
  copy:
    content: "{{ item.key }}"
    dest: "{{ openvpn_user_dir }}/{{ item.name }}/{{ item.name }}.key"
    mode: 0400
    remote_src: true
  loop: "{{ openvpn }}"
  no_log: true

- name: "[NETWORK] Generate ovpn files"
  template:
    src: "{{ item.name }}.ovpn.j2"
    dest: "{{ openvpn_user_dir }}/{{ item.name }}/{{ item.name }}.ovpn"
    mode: 0644
  loop: "{{ openvpn }}"
  no_log: true

- name: "[NETWORK] Copy vpn configurations files to NetworkManager"
  become: true
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
    owner: root
    group: root
  # no_log: true
  loop:
    - src: bbva_vpn.j2
      dest: /etc/NetworkManager/system-connections/BBVA
    - src: bancomer_vpn.j2
      dest: /etc/NetworkManager/system-connections/Datio_CCR
    - src: datio_vpn.j2
      dest: /etc/NetworkManager/system-connections/Datio
