---

- name: "[CHROME] [FEDORA] install google chrome"
  yum:
    name: "{{ chrome_package }}"
    state: present
    update_cache: true

- name: "[CHROME] [UBUNTU] Install gnome extension for chrome"
  yum:
    name: chrome-gnome-shell
    state: present
  when: desktop_environment == "gnome"
