---

install_docker: true
install_dropbox: true
install_code: true
install_spotify: true
install_ohmyzsh: true
install_sublime: true
install_atom: true
install_gitkraken: true
install_telegram: true
install_slack: true
install_forticlientvpn: true
install_tlp: true
install_virtualbox: true
install_pycharm: true
install_keepass: true
install_buttercup: true
install_windscribe: true
install_chrome: true
install_teamviewer: true
install_nomachine: true

tlp_battery_min: 75
tlp_battery_max: 85

atom_latest_url: https://github.com/atom/atom/releases/latest

gitkraken_package:
  fedora: "https://release.axocdn.com/linux/gitkraken-amd64.rpm"
  ubuntu: "https://release.axocdn.com/linux/gitkraken-amd64.deb"

dropbox_package:
  fedora: "https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2019.02.14-1.fedora.x86_64.rpm"
  ubuntu: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb"

# forticlientvpn_ubuntu_packages:
#   - openfortivpn
#   - network-manager-fortisslvpn
#   - network-manager-fortisslvpn-gnome

# forticlientvpn_fedora_packages:
#   - openfortivpn
#   - NetworkManager-fortisslvpn
#   - NetworkManager-fortisslvpn-gnome

ohmyzsh_installer: "https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh"

telegram_flatpak: "https://flathub.org/repo/appstream/org.telegram.desktop.flatpakref"

slack_flatpak: "https://flathub.org/repo/appstream/com.slack.Slack.flatpakref"

pycharm_flatpak: "https://flathub.org/repo/appstream/com.jetbrains.PyCharm-Community.flatpakref"

buttercup_latest_url: https://github.com/buttercup/buttercup-desktop/releases/latest

chrome_package:
  ubuntu: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  fedora: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"

teamviewer_package:
  ubuntu: "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"
  fedora: "https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm"

nomachine_package:
  ubuntu: "https://download.nomachine.com/download/6.7/Linux/nomachine_6.7.6_11_amd64.deb"
  fedora: "https://download.nomachine.com/download/6.7/Linux/nomachine_6.7.6_11_x86_64.rpm"
