---

- name: "[SECRETHUB] [UBUNTU] install repository"
  copy:
    content: "deb [trusted=yes] https://apt.secrethub.io stable main "
    dest: /etc/apt/sources.list.d/secrethub.sources.list

- name: "[SECRETHUB] [UBUNTU] install package"
  apt:
    name: secrethub-cli
    update_cache: true
    state: present
