---

- name: "[DEB] Uninstall old docker packages"
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: "[DEB] Copy repository file"
  template:
    src: docker-ce.list.j2
    dest: /etc/apt/sources.list.d/docker-ce.list
    mode: 0644
    owner: root
    group: root

- name: "[DEB] Import repository key"
  apt_key:
    url: "https://download.docker.com/linux/{{ linux_distribution }}/gpg"
    state: present

- name: "[DEB] Install Docker-CE"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true
