---

- include_tasks: "docker_{{ linux_distribution }}.yml"

- name: "Adding {{ ansible_user }} to group docker"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: "Restart Docker"
  systemd:
    name: docker
    enabled: true
    state: restarted

- name: "Get latest version of Docker Compose"
  uri:
    url: "{{ dockercompose_latest_url }}"
    follow_redirects: safe
    body_format: raw
  register: dockercompose_latest
  when: linux_distribution != "arch"
  tags:
    - install_dockercompose

- name: "Set urls for Docker Compose packages"
  vars:
    dockercompose_version: "{{ dockercompose_latest.url | urlsplit('path') | basename }}"
  set_fact:
    dockercompose_package: "https://github.com/docker/compose/releases/download/{{ dockercompose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
  when: linux_distribution != "arch"
  tags:
    - install_dockercompose

- name: "Download Docker Compose binary"
  get_url:
    url: "{{ dockercompose_package }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  when: linux_distribution != "arch"
  tags:
    - install_dockercompose
