---

- import_tasks: docker_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: dropbox_fedora.yml
  when: ansible_distribution == "Fedora"

- name: "Adding {{ ansible_user_id }} to group docker"
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: "Restart Docker"
  systemd:
    name: docker
    enabled: true
    state: restarted
