---

- include_tasks: "docker_{{ linux_distribution }}.yml"

- name: "Adding {{ ansible_user }} to group docker"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: "Restart Docker"
  systemd:
    name: docker
    enabled: true
    state: restarted
