---

- name: "[UBUNTU] Downlaod Gitkraken package"
  get_url:
    url: "{{ gitkraken_ubuntu_package }}"
    dest: /tmp/gitkraken.deb

- name: "[UBUNTU] Install Gitkraken"
  apt:
    deb: /tmp/gitkraken.deb
    state: present

- name: "[UBUNTU] Delete temporal file"
  file:
    path: /tmp/gitkraken.deb
    state: absent
