---

- name: "[UBUNTU] add ppa repository"
  apt_repository:
    validate_certs: no
    repo: 'ppa:phoerious/keepassxc'
    state: present

- name: "[UBUNTU] install KeepassXC"
  apt:
    name: keepassxc
    state: latest
    update_cache: true
