---

- name: "Get latest version of rambox"
  uri:
    url: "{{ rambox_latest_url }}"
    follow_redirects: safe
    body_format: raw
  register: rambox_latest

- name: "Set urls for rambox packages"
  vars:
    rambox_version: "{{ rambox_latest.url | urlsplit('path') | basename }}"
  set_fact:
    rambox_fedora_package: "https://github.com/ramboxapp/community-edition/releases/download/{{ rambox_version }}/Rambox-{{ rambox_version }}-linux-x86_64.rpm"
    rambox_ubuntu_package: "https://github.com/ramboxapp/community-edition/releases/download/{{ rambox_version }}/Rambox-{{ rambox_version }}-linux-amd64.deb"

- import_tasks: rambox_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: rambox_fedora.yml
  when: ansible_distribution == "Fedora"
