---

- name: "Import repository key"
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: "Install dependencies"
  apt:
    name:
      - apt-transport-https
    state: present
    
- name: "Copy repositort file"
  copy:
    src: sublime.list
    dest: /etc/apt/sources.list.d/sublime.list
    owner: root
    group: root
    mode: 0644

- name: "Install Sublime Text"
  apt:
    name: sublime-text
    state: present
    update_cache: true

