---

- include_tasks: "tlp_{{ linux_distribution }}.yml"

- name: "Configure TLP"
  template:
    src: tlp.j2
    dest: /etc/default/tlp

- name: "Enable TLP systemd services"
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - tlp.service
    - tlp-sleep.service
    - NetworkManager-dispatcher.service
  ignore_errors: true

- name: "Mask TLP system services"
  systemd:
    name: "{{ item }}"
    masked: true
  with_items:
    - systemd-rfkill.service
    - systemd-rfkill.socket
