---

- name: "Install common TLP packages"
  yum:
    name:
      - tlp
      - tlp-rdw
    state: present

- name: "Import repository key"
  rpm_key:
    key: https://repo.linrunner.de/fedora/tlp/repos/RPM-GPG-KEY-tlp-fedora-28-primary
    state: present
  when: "'ThinkPad' in ansible_product_version"

- name: "Install TLP repositories for ThinkPads"
  yum:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc$(rpm -E %fedora).noarch.rpm
    state: present
  when: "'ThinkPad' in ansible_product_version"

- name: "Install TLP packages for ThinkPads"
  yum:
    name:
      - akmod-tp_smapi
      - akmod-acpi_call
      - kernel-devel
    state: present
    update_cache: true
  when: "'ThinkPad' in ansible_product_version"
