---

- name: "[FEDORA] Import repository key"
  rpm_key:
    key: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: "[FEDORA] Create repository file"
  get_url:
    url: https://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo

- name: "[FEDORA] Install Virtualbox and Vagrant packages"
  yum:
    name: "{{ virtualbox_packages }}"
    state: latest
    update_cache: true
