---

- include_vars:
    file: "{{ ansible_distribution | lower }}.yml"

- import_tasks: virtualbox_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: virtualbox_fedora.yml
  when: ansible_distribution == "Fedora"

- name: "Adding {{ ansible_user_id }} to group vboxusers"
  user:
    name: "{{ ansible_user_id }}"
    groups: vboxusers
    append: true
