---

- include_vars:
    file: "{{ linux_distribution }}.yml"

- include_tasks: "virtualbox_{{ linux_distribution }}.yml"

- name: "Adding {{ ansible_user }} to group vboxusers"
  user:
    name: "{{ ansible_user }}"
    groups: vboxusers
    append: true

- name: "Add VAGRANT_DEFAULT_PROVIDER to /etc/profile"
  lineinfile:
    path: /etc/profile
    line: export VAGRANT_DEFAULT_PROVIDER=virtualbox
    state: present
