---

- name: "[1PASSWORD] [FEDORA] Import 1password key"
  rpm_key:
    key: https://onepassword.s3.amazonaws.com/linux/keys/1password.asc
    state: present

- name: "[1PASSWORD] [FEDORA] create reposiotry file"
  copy:
    src: 1password.repo
    dest: /etc/yum.repos.d/1password.repo

- name: "[1PASSWORD] [FEDORA] Install 1password"
  yum:
    name: 1password
    state: present
    update_cache: true
