---

dropbox_dir: "{{ ansible_user_dir }}/Dropbox"
git_dir: "{{ ansible_user_dir }}/git"
git_repositories:
  work:
    - repo: git@globaldevtools.bbva.com:7999/msqlm/msqlm_ops.git
      dest: "{{ git_dir }}/msqlm_ops"
    - repo: git@globaldevtools.bbva.com:7999/mlyid/mlyid_iluvatar.git
      dest: "{{ git_dir }}/iluvatar"
    - repo: git@globaldevtools.bbva.com:7999/msqlm/msqlm_sshmagic.git
      dest: "{{ git_dir }}/ssh_magic"
    - repo: git@globaldevtools.bbva.com:7999/fkrva/fkrva_argos.git
      dest: "{{ git_dir }}/argos"
    - repo: git@globaldevtools.bbva.com:7999/mlyid/mlyid_fsm.git
      dest: "{{ git_dir }}/fsm"
    - repo: git@globaldevtools.bbva.com:7999/mlyid/mlyid_iluvatar_base_image.git
      dest: "{{ git_dir }}/iluvatar_base_image"
    - repo: git@globaldevtools.bbva.com:7999/mlyid/mlyid_docker_nexus_to_artifactory.git
      dest: "{{ git_dir }}/docker_nexus_to_artifactory"
    - repo: git@globaldevtools.bbva.com:7999/mlyid/mlyid_docker_stratio_to_artifactory.git
      dest: "{{ git_dir }}/docker_stratio_to_artifactory"
  home:
    - repo: git@gitlab.com:ohermosa/AmazonPy.git
      dest: "{{ git_dir }}/AmazonPy"
    - repo: git@gitlab.com:ohermosa/BingoPy.git
      dest: "{{ git_dir }}/BingoPy"
    - repo: git@gitlab.com:ohermosa/PiOPs.git
      dest: "{{ git_dir }}/PiOPs"
    - repo: git@gitlab.com:ohermosa/PuedoCircular.git
      dest: "{{ git_dir }}/PuedoCircular"
    - repo: git@gitlab.com:ohermosa/rootnerds.git
      dest: "{{ git_dir }}/rootnerds"
    - repo: git@gitlab.com:ohermosa/whopper_bot.git
      dest: "{{ git_dir }}/whopper_bot"
    - repo: git@gitlab.com:ohermosa/my_workstation.git
      dest: "{{ git_dir }}/my_workstation"



git_user_name: "Oscar Hermosa"
git_user_mail_work: "oscar.hermosa@datiobbva.com"
git_user_mail_personal: "ohermosa@gmail.com"

bbva_user: XE67334

dconf_paths_to_restore:
  - /system/proxy
  - /org/gnome/settings-daemon/peripherals/keyboard
  - /org/gnome/shell
  - /org/gnome/shell/extensions/dash-to-dock
  - /org/gnome/shell/extensions/clipboard-indicator
  - /org/gnome/gedit/preferences/editor
  - /org/gnome/gedit/preferences/ui
  - /org/gnome/gedit/plugins
  - /org/gnome/gedit/state/window
  - /org/gnome/nautilus/preferences
  - /org/gnome/desktop/screensaver
  - /org/gnome/desktop/background
  - /org/gnome/desktop/interface
  - /org/gnome/meld
  - /org/gnome/meld/window-state
  - /org/gtk/settings/file-chooser
  - /com/gexperts/Tilix
  - /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d
  - /com/gexperts/Tilix/keybindings

# dconf_config:
#   - key: "/system/proxy/autoconfig-url"
#     value: "'http://bbvapac.igrupobbva/accelerated_pac_base.pac'"
#   - key: "/system/proxy/mode"
#     value: "'auto'"
#   - key: "/org/gnome/settings-daemon/peripherals/keyboard/numlock-state"
#     value: "'on'"
#   - key: "/org/gnome/shell/app-picker-view"
#     value: "'uint32 1'"
#   - key: "/org/gnome/shell/enabled-extensions"
#     value: "['drive-menu@gnome-shell-extensions.gcampax.github.com', 'clipboard-indicator@tudmotu.com', 'refresh-wifi@kgshank.net'] favorite-apps=['google-chrome.desktop', 'com.gexperts.Tilix.desktop', 'code.desktop', 'org.gnome.Nautilus.desktop', 'forticlient-sslvpn.desktop', 'meld.desktop', 'gitkraken.desktop', 'telegram-desktop_telegramdesktop.desktop', 'spotify_spotify.desktop']"
#   - key: "/org/gnome/shell/enable-hot-corners"
#     value: "false"
#   - key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size"
#     value: "40"
#   - key: "/org/gnome/shell/extensions/clipboard-indicator/notify-on-copy"
#     value: "false"
#   - key: "/org/gnome/shell/extensions/clipboard-indicator/toggle-menu"
#     value: "'<Primary>Down'"
#   - key: "/org/gnome/gedit/preferences/editor/highlight-current-line"
#     value: "true"
#   - key: "/org/gnome/gedit/preferences/editor/display-overview-map"
#     value: "true"
#   - key: "/org/gnome/gedit/preferences/editor/bracket-matching"
#     value: "true"
#   - key: "/org/gnome/gedit/preferences/editor/scheme"
#     value: "'oblivion'"
#   - key: "/org/gnome/gedit/preferences/editor/tabs-size"
#     value: "uint32 4"
#   - key: "/org/gnome/gedit/preferences/editor/display-line-numbers"
#     value: "true"
#   - key: "/org/gnome/gedit/preferences/editor/insert-spaces"
#     value: "true"
#   - key: "/org/gnome/gedit/preferences/editor/wrap-last-split-mode"
#     value: "'word'"
#   - key: "/org/gnome/gedit/preferences/ui/show-tabs-mode"
#     value: "'auto'"
#   - key: "/org/gnome/gedit/plugins/active-plugins"
#     value: "'spell', 'bracketcompletion', 'docinfo', 'wordcompletion', 'multiedit', 'time', 'filebrowser', 'git', 'modelines'"
#   - key: "/org/gnome/gedit/state/window/size"
#     value: "(1541, 700)"
#   - key: "/org/gnome/gedit/state/window/state"
#     value: "43908"
#   - key: "/org/gnome/gedit/state/window/bottom-panel-size"
#     value: "140"
#   - key: "/org/gnome/gedit/state/window/side-panel-size"
#     value: "200"
#   - key: "/org/gnome/gedit/state/window/side-panel-active-page"
#     value: "'GeditWindowDocumentsPanel'"
#   - key: "/org/gnome/nautilus/preferences/default-folder-viewer"
#     value: "'list-view'"
#   - key: "/org/gnome/nautilus/preferences/search-filter-time-type"
#     value: "'last_modified'"
#   - key: "/org/gnome/desktop/screensaver/picture-uri"
#     value: "'file:///usr/share/backgrounds/contest/bionic.xml'"
#   - key: "/org/gnome/desktop/screensaver/primary-color"
#     value: "'#000000000000'"
#   - key: "/org/gnome/desktop/screensaver/picture-options"
#     value: "'zoom'"
#   - key: "/org/gnome/desktop/screensaver/secondary-color"
#     value: "'#000000000000'"
#   - key: "/org/gnome/desktop/background/picture-uri"
#     value: "'file:///usr/share/backgrounds/contest/bionic.xml'"
#   - key: "/org/gnome/desktop/background/show-desktop-icons"
#     value: "false"
#   - key: "/org/gnome/desktop/background/primary-color"
#     value: "'#000000000000'"
#   - key: "/org/gnome/desktop/background/picture-options"
#     value: "'zoom'"
#   - key: "/org/gnome/desktop/background/secondary-color"
#     value: "'#000000000000'"
#   - key: "/org/gnome/desktop/interface/clock-show-date"
#     value: "true"
#   - key: "/org/gnome/desktop/interface/gtk-im-module"
#     value: "'gtk-im-context-simple'"
#   - key: "/org/gnome/desktop/interface/show-battery-percentage"
#     value: "true"
#   - key: "/org/gnome/desktop/interface/icon-theme"
#     value: "'Papirus'"
#   - key: "/org/gnome/desktop/interface/gtk-theme"
#     value: "'Arc-Dark'"
#   - key: "/org/gnome/meld/style-scheme"
#     value: "'solarized-dark'"
#   - key: "/org/gnome/meld/wrap-mode"
#     value: "'none'"
#   - key: "/org/gnome/meld/indent-width"
#     value: "2"
#   - key: "/org/gnome/meld/window-state/width"
#     value: "617"
#   - key: "/org/gnome/meld/window-state/is-fullscreen"
#     value: "false"
#   - key: "/org/gnome/meld/window-state/height"
#     value: "400"
#   - key: "/org/gnome/meld/window-state/is-maximized"
#     value: "true"
#   - key: "/org/gtk/settings/file-chooser/sort-column"
#     value: "'name'"
#   - key: "/org/gtk/settings/file-chooser/sidebar-width"
#     value: "208"
#   - key: "/org/gtk/settings/file-chooser/window-position"
#     value: "(358, 103)"
#   - key: "/org/gtk/settings/file-chooser/show-size-column"
#     value: "true"
#   - key: "/org/gtk/settings/file-chooser/show-hidden"
#     value: "false"
#   - key: "/org/gtk/settings/file-chooser/window-size"
#     value: "(1203, 830)"
#   - key: "/org/gtk/settings/file-chooser/sort-directories-first"
#     value: "true"
#   - key: "/org/gtk/settings/file-chooser/date-format"
#     value: "'regular'"
#   - key: "/org/gtk/settings/file-chooser/sort-order"
#     value: "'ascending'"
#   - key: "/org/gtk/settings/file-chooser/location-mode"
#     value: "'path-bar'"
#   - key: "/com/gexperts/Tilix/new-window-inherit-state"
#     value: "true"
#   - key: "/com/gexperts/Tilix/prompt-on-close"
#     value: "false"
#   - key: "/com/gexperts/Tilix/unsafe-paste-alert"
#     value: "false"
#   - key: "/com/gexperts/Tilix/prompt-on-close-process"
#     value: "false"
#   - key: "/com/gexperts/Tilix/theme-variant"
#     value: "'dark'"
#   - key: "/com/gexperts/Tilix/session-name"
#     value: "'Default${hostname}'"
#   - key: "/com/gexperts/Tilix/use-tabs"
#     value: "true"
#   - key: "/com/gexperts/Tilix/warn-vte-config-issue"
#     value: "false"
#   - key: "/com/gexperts/Tilix/terminal-title-show-when-single"
#     value: "false"
#   - key: "/com/gexperts/Tilix/window-style"
#     value: "'disable-csd-hide-toolbar'"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/foreground-color"
#     value: "'#EFEFEF'"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/visible-name"
#     value: "'Por defecto'"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/palette"
#     value: "['#000000', '#CC0000', '#4D9A05', '#C3A000', '#3464A3', '#754F7B', '#05979A', '#D3D6CF', '#545652', '#EF2828', '#89E234', '#FBE84F', '#729ECF', '#AC7EA8', '#34E2E2', '#EDEDEB']"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/bold-is-bright"
#     value: "false"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/badge-color-set"
#     value: "true"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/default-size-rows"
#     value: "40"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/default-size-columns"
#     value: "160"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/use-system-font"
#     value: "false"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/cursor-colors-set"
#     value: "false"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/highlight-colors-set"
#     value: "false"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/use-theme-colors"
#     value: "false"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/bold-color-set"
#     value: "false"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/font"
#     value: "'Monospace 10'"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/scrollback-unlimited"
#     value: "true"
#   - key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/background-color"
#     value: "'#303030'"
#   - key: "/com/gexperts/Tilix/keybindings/session-add-right"
#     value: "'<Primary><Alt>v'"
#   - key: "/com/gexperts/Tilix/keybindings/app-new-session"
#     value: "'<Primary>n'"
#   - key: "/com/gexperts/Tilix/keybindings/session-synchronize-input"
#     value: "'<Primary><Alt>b'"
#   - key: "/com/gexperts/Tilix/keybindings/session-add-down"
#     value: "'<Primary><Alt>h'"
#   - key: "/com/gexperts/Tilix/keybindings/win-switch-to-next-session"
#     value: "'<Shift>Right'"
#   - key: "/com/gexperts/Tilix/keybindings/win-switch-to-previous-session"
#     value: "'<Shift>Left'"
