---

dropbox_dir: "{{ ansible_user_dir }}/Dropbox"
git_dir: "{{ ansible_user_dir }}/git"
git_repositories:
  work:
    - repo: git@globaldevtools.bbva.com:7999/msqlm/msqlm_ops.git
      dest: "{{ git_dir }}/msqlm_ops"
    - repo: git@globaldevtools.bbva.com:7999/mlyid/mlyid_iluvatar.git
      dest: "{{ git_dir }}/iluvatar"
    - repo: git@globaldevtools.bbva.com:7999/msqlm/msqlm_sshmagic.git
      dest: "{{ git_dir }}/ssh_magic"
    - repo: git@globaldevtools.bbva.com:7999/fkrva/fkrva_argos.git
      dest: "{{ git_dir }}/argos"
    - repo: git@globaldevtools.bbva.com:7999/mlyid/mlyid_fsm.git
      dest: "{{ git_dir }}/fsm"
    - repo: git@globaldevtools.bbva.com:7999/mlyid/mlyid_iluvatar_base_image.git
      dest: "{{ git_dir }}/iluvatar_base_image"
    - repo: git@globaldevtools.bbva.com:7999/mlyid/mlyid_docker_nexus_to_artifactory.git
      dest: "{{ git_dir }}/docker_nexus_to_artifactory"
    - repo: git@globaldevtools.bbva.com:7999/mlyid/mlyid_docker_stratio_to_artifactory.git
      dest: "{{ git_dir }}/docker_stratio_to_artifactory"
  home:
    - repo: git@gitlab.com:ohermosa/AmazonPy.git
      dest: "{{ git_dir }}/AmazonPy"
    - repo: git@gitlab.com:ohermosa/BingoPy.git
      dest: "{{ git_dir }}/BingoPy"
    - repo: git@gitlab.com:ohermosa/PiOPs.git
      dest: "{{ git_dir }}/PiOPs"
    - repo: git@gitlab.com:ohermosa/PuedoCircular.git
      dest: "{{ git_dir }}/PuedoCircular"
    - repo: git@gitlab.com:ohermosa/rootnerds.git
      dest: "{{ git_dir }}/rootnerds"
    - repo: git@gitlab.com:ohermosa/whopper_bot.git
      dest: "{{ git_dir }}/whopper_bot"
    - repo: git@gitlab.com:ohermosa/my_workstation.git
      dest: "{{ git_dir }}/my_workstation"



git_user_name: "Oscar Hermosa"
git_user_mail_work: "oscar.hermosa@datiobbva.com"
git_user_mail_personal: "ohermosa@gmail.com"
