---

- name: "[DROPBOX] [DEB] get latest dropbox version"
  get_dropbox_latest:
    distro: "{{ linux_distribution }}"
    arch: "{{ ansible_architecture }}"
  register: dropbox_version

- debug: var=dropbox_version

- name: "[DROPBOX] [DEB] Install Dropbox package"
  apt:
    deb: "{{ dropbox_package }}"
    state: present
