before_script:
  - echo "before script"

stages:
  - init
  - run-develop
  - run-master

version:
  stage: init
  script:
    - echo "init stage"
  tags:
    - shell
    - gitlab2github

develop:
  stage: run-develop
  script:
    - echo "develop stage"
  tags:
    - shell
    - gitlab2github

run-master:
  stage: run-master
  script:
    - git config --global user.email "${CI_EMAIL}"
    - git config --global user.name "${CI_USERNAME}"
    - git remote remove github; git remote add github https://${GITLAB_USER_LOGIN}:${GITHUB_TOKEN}@gitlab.com/ohermosa/my_workstation.git
    - git remote remove gitea; git remote add gitea https://${GITLAB_USER_LOGIN}:${GITEA_TOKEN}@gitea.com/ohermosa/my_workstation.git
    - git push github
    - git push gitea
  only:
    - master
  tags:
    - shell
    - gitlab2github
