stages:
  - prepare
  - test
  - release

git_config:
  stage: prepare
  before_script:
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - git config push.default simple
    - git remote set-url origin https://gitlab-ci-token:${GITLAB_TOKEN}@${CI_REPOSITORY_URL}
  script:
    - if ! $(git remote show github 2&>1 /dev/null); then git remote add github https://${GITLAB_USER_LOGIN}:${GITHUB_TOKEN}@github.com/ohermosa/my_workstation.git; fi
    - if ! $(git remote show gitea 2&>1 /dev/null); then git remote add gitea https://${GITLAB_USER_LOGIN}:${GITEA_TOKEN}@gitea.com/ohermosa/my_workstation.git; fi
  only:
    - master
  tags:
    - shell
    - gitlab2github

ansible-lint:
  stage: test
  before_script:
    - pip install ansible-lint
  script:
    - ansible-lint ansible/install.yml
  tags:
    - shell
    - gitlab2github

release:
  stage: release
  script:
    - if ! $(git diff-index devel --quiet -- release.json 2&>1 /dev/null); then echo "releasing $(jq -r .version release.json)"; else echo "release.json hasn't changed'"; exit $(git diff-index master --quiet -- release.json); fi
    - git tag -a $(jq -r .version release.json) -m "$(jq -r .version release.json)"
    - git push gitlab --tags
    - git push github
    - git push github --tags
    - git push gitea
    - git push gitea --tags
  only:
    - master
  tags:
    - shell
    - gitlab2github
