stages:
  - test
  - release

ansible-lint:
  stage: test
  before_script:
    - pip install ansible-lint
  script:
    - ansible-lint ansible/install.yml
  except:
    - master
  tags:
    - shell
    - gitlab2github

release:
  stage: release
  before_script:
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - git config push.default simple
    - git remote set-url origin https://${GITLAB_USER_LOGIN}:${GITLAB_TOKEN}@gitlab.com/${GITLAB_USER_LOGIN}/my_workstation.git
    - if ! $(git remote show github 2&>1 /dev/null); then git remote add github https://${GITLAB_USER_LOGIN}:${GITHUB_TOKEN}@github.com/${GITLAB_USER_LOGIN}/my_workstation.git; fi
    - if ! $(git remote show gitea 2&>1 /dev/null); then git remote add gitea https://${GITLAB_USER_LOGIN}:${GITEA_TOKEN}@gitea.com/${GITLAB_USER_LOGIN}/my_workstation.git; fi
  script:
    - git checkout master
    - git pull
    - if ! $(git diff-index HEAD^ --quiet -- release.json 2&>1 /dev/null); then echo "releasing $(jq -r .version release.json)"; else echo "release.json hasn't changed'"; exit $(git diff-index master --quiet -- release.json); fi
    - git tag -a $(jq -r .version release.json) -m "$(jq -r .version release.json)"
    - git push --tags
    - git push github HEAD:master
    - git push github HEAD:master--tags
    - git push gitea HEAD:master
    - git push gitea HEAD:master --tags
  only:
    - master
  tags:
    - shell
    - gitlab2github
