stages:
  - run-develop
  - run-master

ansible-lint:
  stage: run-develop
  before_script:
    - pip install ansible-lint
    - ansible-lint --version
  script:
    - echo "develop stage"
    - ansible-lint ansible/install.yml
  tags:
    - shell
    - gitlab2github

release:
  stage: run-master
  script:
    - git config --global user.email "${CI_EMAIL}"
    - git config --global user.name "${CI_USERNAME}"
    - git remote remove github
    - git remote add github https://${GITLAB_USER_LOGIN}:${GITHUB_TOKEN}@gitlab.com/ohermosa/my_workstation.git
    - git remote remove gitea
    - git remote add gitea https://${GITLAB_USER_LOGIN}:${GITEA_TOKEN}@gitea.com/ohermosa/my_workstation.git
    - git push github --tags
    - git push gitea --tags
  only:
    - master
  tags:
    - shell
    - gitlab2github
