---

- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
  roles:
    - common
    - extra_software
