---

- hosts: localhost
  connection: local
  tasks:
    - import_tasks: load_distro_vars.yml
      tags:
        - always

- hosts: localhost
  connection: local
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
  tasks:
    - name: "Check if there is any config for {{ post_install_user }}"
      stat:
        path: "post_install/{{ post_install_user }}"

    - import_role:
        name: "post_install/{{ post_install_user }}"
