---

- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  tasks:
    - name: "[FEDORA] upgrade all packages to the latest version"
      yum:
        name: '*'
        state: latest
        update_cache: true
      when: ansible_distribution == "Fedora"

    - name: "[UBUNTU] Upgrade all packages to the latest version"
      apt:
        name: "*"
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"
