---

- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  tasks:
    - name: "Update all packages"
      import_role:
        name: common
        tasks_from: update_packages.yml
