---

- name: "[FEDORA] Install common TLP packages"
  yum:
    name:
      - tlp
      - tlp-rdw
    state: latest

- name: "[FEDORA] Import repository key"
  rpm_key:
    key: https://repo.linrunner.de/fedora/tlp/repos/RPM-GPG-KEY-tlp-fedora-28-primary
    state: present
  when: "'ThinkPad' in ansible_product_version"

- name: "[FEDORA] Install TLP repositories for ThinkPads"
  yum:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
      - "http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc{{ fedora_version }}.noarch.rpm"
    state: present
  when: "'ThinkPad' in ansible_product_version"

- name: "[FEDORA] Install TLP packages for ThinkPads"
  yum:
    name:
      - akmod-tp_smapi
      - akmod-acpi_call
      - kernel-devel
    state: latest
    update_cache: true
  when: "'ThinkPad' in ansible_product_version"
