version: "2"
volumes:
  nextcloud:
  db:
  data:
 
services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=UZGVS235rwpbrV45QBdc8Fu9s9cknFRJ
      - MYSQL_PASSWORD=Ci44ATmoJhX5AmXfnIOYKe0fP917eqRs
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
 
  app:
    image: nextcloud
    ports:
      - 8684:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data
    restart: always
