---

common_packages:
  - zeal
  - jq
  - seahorse
  - vim
  - gedit-plugins
  - tilix
  - meld
  - wireshark
  - sshpass
  - git
  - curl
  - wget
  - gimp
  - zeal
  - colordiff
  - htop

ubuntu_packages:
  - libsecret-tools
  - aptitude
  - software-properties-common
  - apt-transport-https
  - vlc
  - network-manager-openvpn
  - network-manager-openvpn-gnome
  - openvpn

fedora_packages:
  - libsecret
  - openvpn
  - NetworkManager-openvpn
  - NetworkManager-openvpn-gnome
  - openvpn
  - NetworkManager-openvpn
  - NetworkManager-openvpn-gnome

bad_snap_packages:
  - gnome-calculator
  - gnome-system-monitor
  - gnome-logs
