---

dropbox_dir: "/home/{{ ansible_user }}/Dropbox"
git_dir: "/home/{{ ansible_user }}/git"
git_repositories:
  work:
    - repo: ssh://git@globaldevtools.bbva.com:7999/msqlm/msqlm_ops.git
      dest: "{{ git_dir }}/msqlm_ops"
    - repo: ssh://git@globaldevtools.bbva.com:7999/msqlm/msqlm_sshmagic.git
      dest: "{{ git_dir }}/ssh_magic"
    # - repo: ssh://git@globaldevtools.bbva.com:7999/fkrva/fkrva_argos.git
    #   dest: "{{ git_dir }}/argos"
    - repo: ssh://git@globaldevtools.bbva.com:7999/mlyid/mlyid_fsm.git
      dest: "{{ git_dir }}/fsm"
    - repo: ssh://git@globaldevtools.bbva.com:7999/mlyid/mlyid_iluvatar.git
      dest: "{{ git_dir }}/iluvatar"
    - repo: ssh://git@globaldevtools.bbva.com:7999/mlyid/mlyid_iluvatar_base_image.git
      dest: "{{ git_dir }}/iluvatar_base_image"
    - repo: ssh://git@globaldevtools.bbva.com:7999/mlyid/mlyid_docker_nexus_to_artifactory.git
      dest: "{{ git_dir }}/docker_nexus_to_artifactory"
    - repo: ssh://git@globaldevtools.bbva.com:7999/mlyid/mlyid_docker_stratio_to_artifactory.git
      dest: "{{ git_dir }}/docker_stratio_to_artifactory"
    - repo: ssh://git@globaldevtools.bbva.com:7999/usoup/usoup_vault_dockerized.git
      dest: "{{ git_dir }}/usoup_vault_dockerized"
  home:
    - repo: git@gitlab.com:ohermosa/AmazonPy.git
      dest: "{{ git_dir }}/AmazonPy"
    - repo: git@gitlab.com:ohermosa/BingoPy.git
      dest: "{{ git_dir }}/BingoPy"
    - repo: git@gitlab.com:ohermosa/PiOPs.git
      dest: "{{ git_dir }}/PiOPs"
    - repo: git@gitlab.com:ohermosa/PuedoCircular.git
      dest: "{{ git_dir }}/PuedoCircular"
    - repo: git@gitlab.com:ohermosa/rootnerds.git
      dest: "{{ git_dir }}/rootnerds"
    - repo: git@gitlab.com:ohermosa/whopper_bot.git
      dest: "{{ git_dir }}/whopper_bot"
    - repo: git@gitlab.com:ohermosa/my_workstation.git
      dest: "{{ git_dir }}/my_workstation"
    - repo: git@gitlab.com:ohermosa/my_k8s.git
      dest: "{{ git_dir }}/my_k8s"
    - repo: git@gitlab.com:ohermosa/kubespray.git
      dest: "{{ git_dir }}/kubespray"
    - repo: git@gitlab.com:ohermosa/raspberrypi.git
      dest: "{{ git_dir }}/raspberrypi"
    - repo: git@github.com:pysto/learning-python-packaging.git
      dest: "{{ git_dir }}/learning-python-packaging"
    - repo: git@github.com:pysto/learning-python-builtins.git
      dest: "{{ git_dir }}/learning-python-builtins"
    - repo: git@github.com:pysto/pykata-scorer.git
      dest: "{{ git_dir }}/pykata-scorer"
    - repo: git@github.com:pysto/openapi-ranker-spec.git
      dest: "{{ git_dir }}/openapi-ranker-spec"

links_to_create:
    - src: "{{ dropbox_dir }}/datio/zshrc"
      dest: "/home/{{ ansible_user }}/.zshrc"
    - src: "{{ dropbox_dir }}/datio/bash_aliases"
      dest: "/home/{{ ansible_user }}/.bash_aliases"
    - src: "{{ dropbox_dir }}/datio/ssh"
      dest: "/home/{{ ansible_user }}/.ssh"
    - src: "{{ dropbox_dir }}/datio/soft"
      dest: "/home/{{ ansible_user }}/soft"
    - src: "{{ dropbox_dir }}/datio/doc"
      dest: "/home/{{ ansible_user }}/doc"
    - src: "{{ dropbox_dir }}/datio/work"
      dest: "/home/{{ ansible_user }}/work"
    - src: "{{ dropbox_dir }}/datio/bashrc"
      dest: "/home/{{ ansible_user }}/.bashrc"
    - src: "{{ dropbox_dir }}/datio/bash_history"
      dest: "{{ ansible_user_dir}}/.bash_history"
    - src: "{{ dropbox_dir }}/datio/ohermosa_molecule-openrc.sh"
      dest: "{{ ansible_user_dir }}/ohermosa_molecule-openrc.sh"
    - src: "{{ dropbox_dir }}/backups/oh-my-zsh_custom_themes"
      dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes"

git_user_name: "Oscar Hermosa"
git_user_mail_work: "oscar.hermosa@datiobbva.com"
git_user_mail_personal: "ohermosa@gmail.com"

bbva_user: XE67334

dconf_paths_to_restore_general:
  - /system/proxy
  - /org/gnome/shell/extensions/dash-to-dock
  - /org/gnome/shell/extensions/clipboard-indicator
  - /org/gnome/meld
  - /org/gnome/meld/window-state
  - /com/gexperts/Tilix
  - /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d
  - /com/gexperts/Tilix/keybindings

dconf_paths_to_restore_ubuntu:
  - /org/gnome/shell
  - /org/gnome/settings-daemon/peripherals/keyboard
  - /org/gtk/settings/file-chooser
  - /org/gnome/nautilus/preferences
  - /org/gnome/desktop/screensaver
  - /org/gnome/desktop/background
  - /org/gnome/desktop/interface
  - /org/gnome/gedit/preferences/editor
  - /org/gnome/gedit/preferences/ui
  - /org/gnome/gedit/plugins
  - /org/gnome/gedit/state/window

fedora_gnome_extensions:
  - "dash-to-dock@micxgx.gmail.com"

gpg_keyserver: pool.sks-keyservers.net
gpg_pub_keys:
  - 3984315D7B289D27BF19B5F2C1FD224DB195D7C9
  - 148410BB2911EF171E1D3AA163A68D889DDC6AF5

wifi_password_1: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30643837393062623933373532636361336263386565623433383535383461383061303961313739
  6139313937663030323461303534663537353039366337650a386330623862376463343834646539
  35623538363565313237353962613139363730386264363138376365383263643934343835306362
  3333343031626565630a623763623732363065633535323161313161336564373763343037653437
  30653266343830343838313732323335396663373533626461333732373530353166
