---

- name: "Get latest version of rambox"
  uri:
    url: "{{ rambox_latest_url }}"
    follow_redirects: safe
    body_format: raw
  register: rambox_latest
  when: linux_distribution != "arch"

- name: "Set urls for rambox packages"
  vars:
    rambox_version: "{{ rambox_latest.url | urlsplit('path') | basename }}"
  set_fact:
    rambox_rpm_package: "https://github.com/ramboxapp/community-edition/releases/download/{{ rambox_version }}/Rambox-{{ rambox_version }}-linux-x86_64.rpm"
    rambox_deb_package: "https://github.com/ramboxapp/community-edition/releases/download/{{ rambox_version }}/Rambox-{{ rambox_version }}-linux-amd64.deb"
  when: linux_distribution != "arch"

- include_tasks: "rambox_{{ linux_distribution }}.yml"
