---

distro_packages:
  - openvpn
  - networkmanager-openvpn
  - libsecret
  - bind-tools
  - net-tools
  - python-libevdev

gnome_arch_packages:
  - wireshark-cli
  - vlc

kde_arch_packages: []

aur_url: https://aur.archlinux.org
yay_repo: "{{ aur_url }}/yay-bin.git"
yay_dir: "/tmp/yay"
