---

distro_packages:
  - libsecret-tools
  - aptitude
  - software-properties-common
  - apt-transport-https
  - vlc
  - openvpn
  - libsecret-tools
  - ubuntu-restricted-extras
  - dnsutils
  - python-dev
  - python3-dev
  - build-essential
  - snap
  - snapd

gnome_ubuntu_packages:
  - network-manager-openvpn
  - network-manager-openvpn-gnome
  - arc-theme
  - elementary-icon-theme
  - papirus-icon-theme
  - gnome-tweaks
  - python-psutil
  - python3-psutil
