---

distro_packages:
  - libsecret-tools
  - aptitude
  - software-properties-common
  - network-manager-openvpn
  - apt-transport-https
  - openvpn
  - dnsutils
  - "{{ 'python-dev' if ubuntu_codename not in ['focal'] else '' }}"
  - python3-dev
  - build-essential
  - snap
  - snapd
  - firewall-config
  - net-tools
  - python3-jmespath
  - "{{ 'python-jmespath' if ubuntu_codename not in ['focal'] else '' }}"
  - python3-gpg
  - secure-delete
  - libnss3-tools
  - libzookeeper-mt-dev
  - fonts-firacode
  - virtualenvwrapper

gnome_ubuntu_packages:
  - ubuntu-restricted-extras
  - network-manager-openvpn-gnome
  - arc-theme
  - elementary-icon-theme
  - papirus-icon-theme
  - gnome-tweaks
  - "{{ 'python-psutil' if ubuntu_codename not in ['focal'] else '' }}"
  - python3-psutil
  - wireshark
  - vlc

kde_ubuntu_packages:
  - kubuntu-restricted-extras
  - kwalletcli
  - usb-creator-kde

xfce_ubuntu_packages:
  - xubuntu-restricted-extras

python_packages:
  - python3
  - python3-pip
  - python3-venv
  - ipython3
  - virtualenvwrapper
