---

- hosts: localhost
  connection: local
  tasks:
    - import_tasks: load_distro_vars.yml
      tags:
        - always

- hosts: all
  become: true
  become_user: root
  roles:
    - common
    - extra_software
