---

- hosts: all
  tasks:
    - import_tasks: load_distro_vars.yml
      tags:
        - always

- hosts: all
  become: true
  become_user: root
  tasks:
    - name: "Check if there is any config for {{ post_install_user }}"
      stat:
        path: "post_install/{{ post_install_user }}"

    - import_role:
        name: "post_install/{{ post_install_user }}"
