---

- name: "[UBUNTU] add ppa repository"
  apt_repository:
    validate_certs: no
    repo: 'ppa:ansible/ansible'
    state: present
    codename: "{{ ubuntu_codename }}"

- name: "[UBUNTU] Update ansible"
  apt:
    name:
      - ansible
      - python-apt
    update_cache: true
    state: latest
