---

- name: "[ARCH] Install common packages"
  pacman:
    name: "{{ common_packages }}"
    state: latest
    update_cache: true

- name: "[ARCH] Install Arch packages"
  pacman:
    name: "{{ distro_packages }}"
    state: latest
    update_cache: true

- name: "[ARCH] Install Gnome packages"
  pacman:
    name: "{{ gnome_packages }} + {{ gnome_fedora_packages }}"
    state: latest
    update_cache: true
  when:
    - desktop_environment is defined
    - desktop_environment == "gnome"

- name: "[ARCH] Install KDE packages"
  pacman:
    name: "{{ kde_packages }} + {{ kde_fedora_packages }}"
    state: latest
    update_cache: true
  when:
    - desktop_environment is defined
    - desktop_environment == "kde"
