---

- name: "[ARCH] Install common packages"
  pacman:
    name: "{{ common_packages }}"
    state: present
    update_cache: true

- name: "[ARCH] Install Arch packages"
  pacman:
    name: "{{ distro_packages }}"
    state: present
    update_cache: true

- name: "[ARCH] Install Gnome packages"
  pacman:
    name: "{{ gnome_packages }} + {{ gnome_arch_packages }}"
    state: present
    update_cache: true
  when:
    - desktop_environment is defined
    - desktop_environment == "gnome"

- name: "[ARCH] Install KDE packages"
  pacman:
    name: "{{ kde_packages }} + {{ kde_arch_packages }}"
    state: present
    update_cache: true
  when:
    - desktop_environment is defined
    - desktop_environment == "kde"

- name: "[ARCH] install kwalletcli package"
  become: false
  yay:
    name: "{{ kwalletcli_package }}"
    state: present
    update_cache: true

- name: "[ARCH] Install XFCE packages"
  pacman:
    name: "{{ xfce_packages }} + {{ xfce_arch_packages }}"
    state: present
    update_cache: true
  when:
    - desktop_environment is defined
    - desktop_environment == "xfce"
