---

- name: "[FEDORA] Install common packages"
  yum:
    name: "{{ common_packages }}"
    state: present
    update_cache: true

- name: "[FEDORA] Install Fedora packages"
  yum:
    name: "{{ distro_packages }}"
    state: present
    update_cache: true

- name: "[FEDORA] Install Gnome packages"
  yum:
    name: "{{ gnome_packages }} + {{ gnome_fedora_packages }}"
    state: present
    update_cache: true
  when:
    - desktop_environment is defined
    - desktop_environment == "gnome"

- name: "[FEDORA] Install KDE packages"
  yum:
    name: "{{ kde_packages }} + {{ kde_fedora_packages }}"
    state: present
    update_cache: true
  when:
    - desktop_environment is defined
    - desktop_environment == "kde"

- name: "[FEDORA] Install XFCE packages"
  yum:
    name: "{{ xfce_packages }} + {{ xfce_fedora_packages }}"
    state: present
    update_cache: true
  when:
    - desktop_environment is defined
    - desktop_environment == "xfce"

- import_tasks: vlc_fedora.yml
  tags:
    - vlc
