---

- import_tasks: update_packages.yml
  tags:
    - always
  ignore_errors: true

- import_tasks: selinux.yml
  when: linux_distribution == "fedora"
  tags:
    - common
    - disable_selinux

- include_vars:
    file: "{{ item }}"
  loop:
    - "{{ linux_distribution | lower }}.yml"
    - "{{ desktop_environment | lower }}.yml"
  tags:
    - common
    - install_packages

- include_tasks:
    file: "install_packages_{{ linux_distribution }}.yml"
    apply:
      tags:
        - common
        - install_packages
  tags:
    - common
    - install_packages

- include_tasks:
    file: "ansible_{{ linux_distribution }}.yml"
    apply:
      tags:
        - common
        - ansible
  tags:
    - common
    - ansible

- import_tasks: python.yml
  tags:
    - common
    - python
    - python3

- import_tasks: delete_snap.yml
  when: ansible_distribution == "ubuntu" and ansible_distribution_major_version >= "18"
  tags:
    - common
    - delete_snap

- name: "Configure /etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }}\t{{ item.host }}"
  loop: "{{ etc_hosts }}"
  tags:
    - common
    - resolv

- name: "Configure size of bash history"
  lineinfile:
    path: /etc/profile
    line: "{{ item }}"
  loop:
    - 'export HISTTIMEFORMAT="%d/%m - %H:%M:%S "'
    - 'export HISTSIZE=50000'
  tags:
    - common
    - bash_history_size
