---

- import_tasks: update_packages.yml
  tags:
    - always

- import_tasks: selinux.yml
  when: linux_distribution == "fedora"
  tags:
    - common
    - disable_selinux

- include_vars:
    file: "{{ linux_distribution | lower }}.yml"
  tags:
    - common
    - install_packages
    - yay

- include_vars:
    file: "{{ desktop_environment | lower }}.yml"
  when: desktop_environment is defined
  tags:
    - common
    - install_packages

- include_tasks:
    file: "install_packages_{{ linux_distribution }}.yml"
    apply:
      tags:
        - common
        - install_packages
  tags:
    - common
    - install_packages

- include_tasks:
    file: "ansible_{{ linux_distribution }}.yml"
    apply:
      tags:
        - common
        - ansible
  tags:
    - common
    - ansible

- import_tasks: python.yml
  tags:
    - common
    - python
    - python3

- import_tasks: delete_snap.yml
  when: ansible_distribution == "ubuntu" and ansible_distribution_major_version >= "18"
  tags:
    - common
    - delete_snap

- name: "[ARCH] install yay package"
  import_tasks: yay.yml
  when: linux_distribution == "arch"
  tags:
    - common
    - yay

- name: "Configure size of bash history"
  lineinfile:
    path: /etc/profile
    line: "{{ item }}"
  loop:
    - 'export HISTTIMEFORMAT="%d/%m - %H:%M:%S "'
    - 'export HISTSIZE=50000'
  tags:
    - common
    - bash_history_size
