---

- name: "[FEDORA] Install Python3"
  yum:
    name: "{{ python_packages }}"
    state: latest
    update_cache: true
  when: linux_distribution == "fedora"

- name: "[UBUNTU] Install Python3"
  apt:
    name: "{{ python_packages }}"
    state: latest
    update_cache: true
  when: linux_distribution == "ubuntu"

- name: "[DEBIAN] Install Python3"
  apt:
    name: "{{ python_packages }}"
    state: latest
    update_cache: true
  when: linux_distribution == "debian"

- name: "[ARCH] Install Python3"
  pacman:
    name: "{{ python_packages }}"
    state: latest
    update_cache: true
  when: linux_distribution == "arch"

- name: "Alternative link for python"
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
  when: linux_distribution != "arch"

- name: "Alternative link for pip"
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3
  when: linux_distribution != "arch"

- name: "Install setuptools python module"
  pip:
    name:
      - setuptools
    extra_args: --user

- name: "Install python modules"
  pip:
    name:
      - mega.py
      - telepot
      - matplotlib
      - numpy
      - beautifulsoup4
      - bs4
      - openstacksdk
      - molecule
      - dnspython
      - docker-py
      - virtualenvwrapper
    extra_args: --user
