---

- name: "Alternative link for python"
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
  when: linux_distribution != "arch"

- name: "Alternative link for pip"
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3
  when: linux_distribution != "arch"

- name: "Install setuptools python module"
  pip:
    name:
      - setuptools

- name: "Install python modules"
  pip:
    name: "{{ python_modules }}"
