---

- name: "[UBUNTU] Upgrade all packages to the latest version"
  apt:
    name: "*"
    state: latest
    # update_cache: true
    force_apt_get: true
    autoclean: true
  when: linux_distribution in ["debian", "ubuntu"]

- name: "[FEDORA] upgrade all packages to the latest version"
  yum:
    name: '*'
    state: latest
    update_cache: true
  when: linux_distribution == "fedora"

- name: "[ARCH] upgrade all packages to the latest version"
  pacman:
    update_cache: yes
    upgrade: yes
  ignore_errors: true
  when: linux_distribution == "arch"

- name: "Create {{ last_update_file }}"
  file:
    path: "{{ last_update_file }}"
    state: touch
