---

- include_vars:
    file: "{{ linux_distribution }}.yml"

- name: "[ARCH] uninstall yay and yay-bin"
  pacman:
    name:
      - yay
      - yay-bin
    state: absent

- name: "[ARCH] clone yay repository"
  become: false
  git:
    repo: "{{ yay_repo }}"
    dest: "{{ yay_dir }}"
    clone: yes

- name: "[ARCH] install yay package"
  become: false
  shell: makepkg -si --noconfirm
  args:
    chdir: "{{ yay_dir }}"
