---

- name: "[FEDORA] Install zsh"
  yum:
    name: zsh
    state: latest
  when: linux_distribution == "fedora"

- name: "[DEB] Install zsh"
  apt:
    name: zsh
    state: latest
  when: linux_distribution in ["ubuntu", "debian"]

- name: "[ARCH] Install zsh"
  pacman:
    name: zsh
    state: latest
  when: linux_distribution == "arch"
