---

- name: "[VAULT] [FEDORA] download hashicorp.repo"
  get_url:
    url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: "[VAULT] [FEDORA] install vault package"
  yum:
    name: vault
    update_cache: true
    state: present
