---

- name: "[VAULT] [ARCH] Install vault"
  become: false
  yay:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ vault_package }}"
    - "{{ vault_cli_package }}"
