---

install_docker: true
install_dropbox: true
install_code: true
install_spotify: true
install_ohmyzsh: true
install_sublime: true
install_atom: true
install_gitkraken: true
install_telegram: true
install_slack: true
install_forticlientvpn: true
install_tlp: true
install_virtualbox: true
install_pycharm: true
install_keepass: true
install_buttercup: true
install_windscribe: true
install_chrome: true
install_teamviewer: true
install_nomachine: true
install_ecs: true
install_postman: true
install_skype: true
install_java: true
install_apachedirectory: true
install_rambox: true
install_franz: true
install_chromium: true
install_deluge: true
install_cherrytree: true
install_kubectl: true
install_flatpak: true
install_megacmd: true
install_megasync: true
install_vivaldi: true
install_brave: true
install_bitwarden: true
install_lexnet: false
install_pass: true
install_bucklespring: false
install_protonvpn: true
install_prezto: true
install_etcher: true
install_woeusb: true
install_go: true
install_fzf: true
install_vimplugins: true

tlp_battery_min: 75
tlp_battery_max: 85

atom_latest_url: "https://github.com/atom/atom/releases/latest"
rambox_latest_url: "https://github.com/ramboxapp/community-edition/releases/latest"
buttercup_latest_url: "https://github.com/buttercup/buttercup-desktop/releases/latest"
franz_latest_url: "https://github.com/meetfranz/franz/releases/latest"
dockercompose_latest_url: "https://github.com/docker/compose/releases/latest"
bitwarden_latest_url: "https://github.com/bitwarden/desktop/releases/latest"
bitwardencli_latest_url: "https://github.com/bitwarden/cli/releases/latest"
helm_latest_url: "https://github.com/helm/helm/releases/latest"
hetznerkube_latest_url: "https://github.com/xetys/hetzner-kube/releases/latest"
etcher_latest_url: "https://github.com/balena-io/etcher/releases/latest"
fzf_latest_url: "https://github.com/junegunn/fzf-bin/releases/latest"

ohmyzsh_installer: "https://gitlab.com/ohermosa/oh-my-zsh/raw/master/tools/install.sh"

telegram_flatpak: "https://flathub.org/repo/appstream/org.telegram.desktop.flatpakref"
slack_flatpak: "https://flathub.org/repo/appstream/com.slack.Slack.flatpakref"
pycharm_flatpak: "https://flathub.org/repo/appstream/com.jetbrains.PyCharm-Community.flatpakref"
postman_flatpak: "https://flathub.org/repo/appstream/com.getpostman.Postman.flatpakref"
skype_flatpak: "https://flathub.org/repo/appstream/com.skype.Client.flatpakref"
franz_flatpak: "https://flathub.org/repo/appstream/com.meetfranz.Franz.flatpakref"

ecs_cli_package: "ecs-cli-0.2.16.tar.gz"
ecs_cli_url: "https://globaldevtools.bbva.com/artifactory/semaas-global-bin/releases/ecs-cli/{{ ecs_cli_package }}"
ecs_cli_doc_url: "https://platform.bbva.com/en-us/developers/ether-cli/documentation/03-getting-started"

apachedirectory_url: "http://ftp.cixug.es/apache/directory/studio/2.0.0.v20180908-M14/ApacheDirectoryStudio-2.0.0.v20180908-M14-linux.gtk.x86_64.tar.gz"

deluge_package: deluge
cherrytree_package: cherrytree

virtualbox_extpack_version: "6.0.14"

mega_url_base: "https://mega.nz/linux/MEGAsync"

vivaldi_version: 2.9.1705.41-1

prezto_repo: https://github.com/sorin-ionescu/prezto.git

go_dir: /usr/local/go

vim_plugins:
  - 'VundleVim/Vundle.vim'
  - 'itchyny/lightline.vim'
  - 'preservim/nerdtree'
  - 'altercation/vim-colors-solarized'
  - 'pearofducks/ansible-vim'
  - 'frazrepo/vim-rainbow'
  - 'junegunn/fzf.vim'
  # - 'lokaltog/vim-powerline'
  - 'airblade/vim-gitgutter'
  - 'terryma/vim-multiple-cursors'
  - 'mileszs/ack.vim'
  - 'kien/ctrlp.vim'
  - 'vim-scripts/AutoComplPop'

firefox_esr_version: 50.1.0
firefox_esr_url: "https://download-installer.cdn.mozilla.net/pub/firefox/releases/{{ firefox_esr_version }}/linux-x86_64/es-ES/firefox-{{ firefox_esr_version }}.tar.bz2"
firefox_esr_dir: /opt/firefox
firefox_esr_binary: "{{ firefox_esr_dir }}/firefox"
java_lexnet_package: "https://descargas.lexdefensa.es/jdk-8u241-linux-x64.tar.gz"
lexnet_firefox_profile: lexnet
lexnet_packages:
  - libccid
  - libpcsclite1
  - pcscd
  - pcsc-tools
  - libglade2-dev

code_extensions_urls: https://gist.githubusercontent.com/ohermosa/a2b55c8a488b2a45e8626e75ca35c7c4/raw/e647bfa074c16982c533c3ffaa38dffa83c392a8/extensions.json
