---

# forticlientvpn_packages:
#   - openfortivpn
#   - network-manager-fortisslvpn
#   - network-manager-fortisslvpn-gnome

gitkraken_package: "https://release.axocdn.com/linux/gitkraken-amd64.deb"
dropbox_package: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb"
chrome_package: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
teamviewer_package: "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"
nomachine_package: "https://download.nomachine.com/download/6.7/Linux/nomachine_6.7.6_11_amd64.deb"
