version: '3'
services:
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: changeme
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    restart: on-failure
    volumes:
     - /var/tmp/mariadb:/var/lib/mysql
    container_name: mariadb
