---

- name: "[FORTICLIENTVPN] [DEB] install forticlient package"
  apt:
    deb: "{{ forticlient_deb_package }}"
    update_cache: true
    state: present
  when: ansible_distribution == "Ubuntu"

- name: "[FORTICLIENTVPN] [DEB] install dnsmasq"
  apt:
    name: dnsmasq
    state: present
  when: ansible_distribution == "Ubuntu"

- name: "[FORTICLIENTVPN] [DEB] copy dnmasq configfile"
  copy:
    src: vpnaas.conf
    dest: /etc/dnsmasq.d

- name: "[FORTICLIENTVPN] [DEB] Stop NetworkManager"
  systemd:
    name: NetworkManager
    state: stopped

- name: "[FORTICLIENTVPN] [DEB] reconfigure NetworkManager.conf"
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    insertafter: "^plugins=ifupdown,keyfile"
    line: "dns=none"
    state: present

- name: "[FORTICLIENTVPN] [DEB] delete /etc/resolv.conf"
  file:
    path: /etc/resolv.conf
    state: absent

- name: "[FORTICLIENTVPN] [DEB] create empty /etc/resolv.conf"
  file:
    path: /etc/resolv.conf
    state: touch

- name: "[FORTICLIENTVPN] [DEB] restart NetworkManager"
  systemd:
    name: NetworkManager
    state: restarted

- name: "[FORTICLIENTVPN] [DEB] disable systemd-resolved"
  systemd:
    name: systemd-resolved
    enabled: false
    state: stopped

- name: "[FORTICLIENTVPN] [DEB] enable dnsmasq"
  systemd:
    name: dnsmasq
    state: started
    enabled: true

- name: "[FORTICLIENTVPN] [DEB] copy script rutas"
  copy:
    src: rutas_vpnaas
    dest: /usr/local/bin/rutas_vpnaas
    mode: 0755
