---

- include_tasks: "forticlientvpn_{{ linux_distribution }}.yml"

- name: "[FORTICLIENTVPN] Copy rutas.sh to /home/{{ ansible_user }}"
  template:
    src: rutas.sh.j2
    dest: "/home/{{ ansible_user }}/rutas.sh"
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
