---

git_dir: "{{ ansible_user_dir }}/git"

docker:
  insecure_registries:
    - "10.48.193.182"
    - "10.48.228.157"
    - "idev2:5000"
    - "172.16.48.147:5000"
    - "10.48.238.129:5000"
    - "10.142.248.49:443"
    - "10.48.235.188:443"
    - "172.16.50.69:443"
    - "nonexus.asgard.es.datio"
    - "nonexus.aws.es.datio"
    - "nexus.atlantis.es.datio"
    - "nexus.daas.work.es.ether.igrupobbva"
    - "nexus.daas.live.es.ether.igrupobbva"
    - "localhost:5000"
    - "nexus.daas-mx-dpy-02.ext.mx.iaas.igrupobbva"
    - "nexus.daas-mx-dpy-01.ext.mx.iaas.igrupobbva"

datio_vpns:
  - datio
  - bancomer
  - bbva

datio_vpn_config:
  host: spain.datio.com
  port: 1194

bbva_vpn_config:
  host: spain.datio.com
  port: 1195

bancomer_vpn_config:
  host: 200.66.87.82
  port: 1195
