---

- name: "[UBUNTU] Check if ansible_version >= 2.8"
  assert:
    that:
      - ansible_version.full >= "2.8"
    fail_msg: "Ansible version must be >= 2.8. Please, ejecute 'ansible-playbook update_ansible.yml --ask-become-pass'"
    success_msg: "OK, your ansible version is {{ ansible_version.full }}"

- name: "[UBUNTU] Install Slack using snap"
  snap:
    name:
      - slack
    state: present
    classic: true
