---

- include_vars:
    file: "{{ linux_distribution }}.yml"

- include_tasks: "deluge_{{ linux_distribution }}.yml"

- name: "Create deluge config directory"
  file:
    path: "/home/{{ ansible_user }}/.config/deluge/"
    state: directory

- name: "Basic Deluge configuration"
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/.config/deluge/{{ item.dest }}"
  loop:
    - src: deluge.core.conf.j2
      dest: core.conf
    - src: deluge.gtkui.conf.j2
      dest: gtkui.conf
