---

- name: "Uninstall old docker packages"
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: "Copy repository file"
  copy:
    src: docker-ce.list
    dest: /etc/apt/sources.list.d/docker-ce.list
    mode: 0644
    owner: root
    group: root

- name: "Import repository key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Install Docker-CE"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
