---

- name: "Uninstall old docker"
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent

- name: "Copy repository file for Docker-CE"
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
    owner: root
    group: root

- name: "Install Docker"
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
