---

- name: "delete firefox and java directories"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /opt/jdk
    - /opt/firefox

- name: "create directories"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/jdk
    - /opt/firefox

- name: "Uncompress firefox 'lexnet edition'"
  unarchive:
    src: "{{ firefox_url }}"
    dest: "/opt/firefox"
    remote_src: true

- name: "uncompress java"
  unarchive:
    src: https://descargas.lexdefensa.es/jdk-8u241-linux-x64.tar.gz
    dest: /opt/jdk
    remote_src: true

- name: "update java alternatives"
  alternatives:
    name: "{{ item.name }}"
    link: "{{ item.link }}"
    path: "{{ item.path }}"
    priority: "{{ item.priority }}"
  loop:
    - name: java
      link: /usr/bin/java
      path: /opt/jdk/jdk1.8.0_241/bin/java
      priority: 100
    - name: javac
      link: /usr/bin/javac
      path: /opt/jdk/jdk1.8.0_241/bin/javac
      priority: 100

- name: "create firefox plugins directory"
  file:
    path: /opt/firefox/firefox/browser/plugins
    state: directory

- name: "create link to java plugin"
  file:
    src: /opt/jdk/jdk1.8.0_241/jre/lib/amd64/libnpjp2.so
    dest: /opt/firefox/firefox/browser/plugins/libnpjp2.so
    state: link

- name: "check if {{ ansible_user_dir }}/.mozilla/firefox exists"
  stat:
    path: "{{ ansible_user_dir }}/.mozilla/firefox"
  register: stat_response

- name: "customize firefox if {{ ansible_user_dir }}/.mozilla/firefox exists"
  block:
    - name: "get the firefox preferences file"
      find:
        path: "{{ ansible_user_dir }}/.mozilla/firefox"
        patterns: "^prefs.js$"
        use_regex: true
        file_type: file
        recurse: true
      register: find_response

    - name: "customize firefox profile for {{ ansible_user }}"
      lineinfile:
        path: "{{ (find_response.files | json_query('[].path'))[0] }}"
        line: 'user_pref("plugin.load_flash_only", false);'
  when: stat_response.stat.exists
