---

- name: "Get latest version of fzf"
  uri:
    url: "{{ fzf_latest_url }}"
    follow_redirects: safe
    body_format: raw
  register: fzf_latest

- name: "Set url for fzf package"
  vars:
    fzf_version: "{{ fzf_latest.url | urlsplit('path') | basename }}"
  set_fact:
    fzf_package: "https://github.com/junegunn/fzf-bin/releases/download/{{ fzf_version }}/fzf-{{ fzf_version }}-linux_amd64.tgz"

- name: "Download fzf"
  unarchive:
    src: "{{ fzf_package }}"
    dest: /usr/local/bin
    remote_src: true
    mode: 0755
