---

- name: "[FZF] [DEB] install fzf"
  apt:
    name: fzf
    update_cache: true
    state: present
  when: linux_distribution == "ubuntu"

- name: "[FZF] [FEDORA] install fzf"
  yum:
    name: fzf
    update_cache: true
    state: present
  when: linux_distribution == "fedora"

- name: "[FZF] [ARCH] install fzf"
  pacman:
    name: fzf
    state: present
    update_cache: true
  when: linux_distribution == "arch"
