---

- name: "check if previous version is installed"
  stat:
    path: "{{ go_dir }}"
  register: go_response

- name: "delete previous version if exists"
  file:
    path: "{{ go_dir }}"
    state: absent
  when: go_response.stat.exists

- name: "get latest go version"
  get_go_latest:
  register: go_response

- name: "download go {{ go_response.version }}"
  unarchive:
    src: "https://dl.google.com/go/go{{ go_response.version }}.linux-amd64.tar.gz"
    dest: "/usr/local"
    remote_src: true

- name: "get the default shell for {{ ansible_user }}"
  become: false
  shell: "basename $(echo $SHELL)"
  register: shell_response
  changed_when: false

- name: "modify PATH variable"
  become: false
  lineinfile:
    path: "{{ ansible_user_dir }}/.{{ shell_response.stdout }}rc"
    line: "export PATH=$PATH:/usr/local/go/bin"
    state: present
