---

- name: "install lexnet dependencies"
  apt:
    name: "{{ lexnet_packages }}"
    state: present
    update_cache: true
    autoclean: true

- name: "delete firefox and java directories"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /opt/jdk
    - "{{ firefox_esr_dir }}"

- name: "create java directory"
  file:
    path: /opt/jdk
    state: directory

- name: "Uncompress firefox ESR 50"
  unarchive:
    src: "{{ firefox_url }}"
    dest: "/opt"
    remote_src: true

- name: "uncompress java"
  unarchive:
    src: https://descargas.lexdefensa.es/jdk-8u241-linux-x64.tar.gz
    dest: /opt/jdk
    remote_src: true

- name: "update java alternatives"
  alternatives:
    name: "{{ item.name }}"
    link: "{{ item.link }}"
    path: "{{ item.path }}"
    priority: "{{ item.priority }}"
  loop:
    - name: java
      link: /usr/bin/java
      path: /opt/jdk/jdk1.8.0_241/bin/java
      priority: 100
    - name: javac
      link: /usr/bin/javac
      path: /opt/jdk/jdk1.8.0_241/bin/javac
      priority: 100

- name: "create firefox plugins directory"
  file:
    path: "{{ firefox_esr_dir }}/browser/plugins"
    state: directory

- name: "create link to java plugin"
  file:
    src: /opt/jdk/jdk1.8.0_241/jre/lib/amd64/libnpjp2.so
    dest: "{{ firefox_esr_dir }}/browser/plugins/libnpjp2.so"
    state: link

- name: "check if {{ ansible_user_dir }}/.mozilla/firefox exists"
  stat:
    path: "{{ ansible_user_dir }}/.mozilla/firefox"
  register: stat_response

- name: "customize firefox if {{ ansible_user_dir }}/.mozilla/firefox exists"
  become: false
  become_user: "{{ ansible_user }}"
  block:
    - name: "generate new profile {{ lexnet_firefox_profile }}"
      shell: "{{ item }}"
      loop:
        - "{{ firefox_esr_binary }} -CreateProfile {{ lexnet_firefox_profile }}"
        - "{{ firefox_esr_binary }} -P {{ lexnet_firefox_profile }} &"
        - "killall firefox"

    - name: "get the firefox preferences file"
      find:
        path: "{{ ansible_user_dir }}/.mozilla/firefox"
        patterns: "^prefs.js$"
        use_regex: true
        file_type: file
        recurse: true
      register: find_response

    - name: "customize firefox profile for {{ ansible_user }}"
      lineinfile:
        path: "{{ item }}"
        line: 'user_pref("plugin.load_flash_only", false);'
      when: lexnet_firefox_profile in item
      loop: "{{ find_response.files | json_query('[].path') }}"
  when: stat_response.stat.exists
