---

- include_vars:
    file: "{{ linux_distribution }}.yml"
  tags:
    - always

- name: "---[INSTALL]--- flatpak"
  import_tasks: flatpak.yml
  when:
    - linux_distribution == "fedora"
    - install_flatpak
  tags:
    - extra_software
    - install_flatpak
    - install_telegram
    - install_slack
    - install_pycharm
    - install_postman
    - install_skype
    - install_franz
    - ohermosa

- name: "---[INSTALL]--- docker"
  import_tasks: docker/docker.yml
  when: install_docker
  tags:
    - extra_software
    - install_docker
    - ohermosa

- name: "---[INSTALL]--- dropbox"
  import_tasks: dropbox/dropbox.yml
  when: install_dropbox
  tags:
    - extra_software
    - install_dropbox
    - ohermosa

- name: "---[INSTALL]--- Visual Studio Code"
  import_tasks: code/code.yml
  when: install_code
  tags:
    - extra_software
    - install_code
    - install_editors
    - ohermosa

- name: "---[INSTALL]--- Spotify"
  import_tasks: spotify/spotify.yml
  when: install_spotify
  tags:
    - extra_software
    - install_spotify
    - ohermosa

- name: "---[INSTALL]--- Oh My ZSH!"
  import_tasks: oh_my_zsh.yml
  when:
    - install_ohmyzsh
  tags:
    - extra_software
    - install_ohmyzsh
    - ohermosa

- name: "---[INSTALL]--- Sublime Text"
  import_tasks: sublime/sublime.yml
  when: install_sublime
  tags:
    - extra_software
    - install_sublime
    - install_editors

- name: "---[INSTALL]--- Atom"
  import_tasks: atom/atom.yml
  when: install_atom
  tags:
    - extra_software
    - install_atom
    - install_editors

- name: "---[INSTALL]--- Gitkraken"
  import_tasks: gitkraken/gitkraken.yml
  when: install_gitkraken
  tags:
    - extra_software
    - install_gitkraken
    - ohermosa

- name: "---[INSTALL]--- Telegram"
  import_tasks: telegram/telegram.yml
  when: install_telegram
  tags:
    - extra_software
    - install_telegram
    - install_socials
    - ohermosa

- name: "---[INSTALL]--- Slack"
  import_tasks: slack/slack.yml
  when: install_slack
  tags:
    - extra_software
    - install_slack
    - install_socials

- name: "---[INSTALL]--- Forticlient VPN"
  import_tasks: forticlientvpn/forticlientvpn.yml
  when: install_forticlientvpn
  tags:
    - extra_software
    - install_forticlientvpn
    - install_vpnclient

- name: "---[INSTALL]--- TLP"
  import_tasks: tlp/tlp.yml
  when: install_tlp
  tags:
    - extra_software
    - install_tlp

- name: "---[INSTALL]--- Virtualbox"
  import_tasks: virtualbox/virtualbox.yml
  when: install_virtualbox
  tags:
    - extra_software
    - install_virtualbox
    - ohermosa

- name: "---[INSTALL]--- PyCharm"
  import_tasks: pycharm/pycharm.yml
  when: install_pycharm
  tags:
    - extra_software
    - install_pycharm
    - install_editors

- name: "---[INSTALL]--- Keepass"
  import_tasks: keepass/keepass.yml
  when: install_keepass
  tags:
    - extra_software
    - install_keepass
    - install_pass_managers

- name: "---[INSTALL]--- Buttercup"
  import_tasks: buttercup/buttercup.yml
  when: install_buttercup
  tags:
    - extra_software
    - install_buttercup
    - install_pass_managers

- name: "---[INSTALL]--- Windscribe client"
  import_tasks: windscribe/windscribe.yml
  when: install_windscribe
  tags:
    - extra_software
    - install_windscribe
    - install_vpnclient

- name: "---[INSTALL]--- Google Chrome"
  import_tasks: chrome/chrome.yml
  when: install_chrome
  tags:
    - extra_software
    - install_chrome
    - ohermosa

- name: "---[INSTALL]--- Teamviewer"
  import_tasks: teamviewer/teamviewer.yml
  when: install_teamviewer
  tags:
    - extra_software
    - install_teamviewer
    - ohermosa

- name: "---[INSTALL]--- No Machine"
  import_tasks: nomachine/nomachine.yml
  when: install_nomachine
  tags:
    - extra_software
    - install_nomachine
    - install_remotes

- name: "---[INSTALL]--- Ether Cloud Services Client"
  import_tasks: ecs.yml
  when: install_ecs
  tags:
    - extra_software
    - install_ecs

- name: "---[INSTALL]--- Postman"
  import_tasks: postman/postman.yml
  when: install_postman
  tags:
    - extra_software
    - install_postman

- name: "---[INSTALL]--- Skype"
  import_tasks: skype/skype.yml
  when: install_skype
  tags:
    - extra_software
    - install_skype

- name: "---[INSTALL]--- Java"
  import_tasks: java/java.yml
  when: install_java
  tags:
    - extra_software
    - install_java
    - install_apachedirectory

- name: "---[INSTALL]--- Apache Directory"
  block:
    - import_tasks: apachedirectory.yml
      when:
        - install_apachedirectory
        - linux_distribution != "arch"

    - name: "[ARCH] Install apache directory studio"
      become: false
      yay:
        name: "{{ apachedirectory_package }}"
        state: present
        update_cache: true
      when:
        - install_apachedirectory
        - linux_distribution == "arch"
  tags:
    - extra_software
    - install_apachedirectory

- name: "---[INSTALL]--- Rambox"
  import_tasks: rambox/rambox.yml
  when: install_rambox
  tags:
    - extra_software
    - install_rambox

- name: "---[INSTALL]--- Franz"
  import_tasks: franz/franz.yml
  when: install_franz
  tags:
    - extra_software
    - install_franz

- name: "---[INSTALL]--- Chromium Browser"
  import_tasks: chromium/chromium.yml
  when: install_chromium
  tags:
    - extra_software
    - install_chromium

- name: "---[INSTALL]--- Deluge"
  import_tasks: deluge/deluge.yml
  when:
    - install_deluge
    - desktop_environment == "gnome"
  tags:
    - extra_software
    - install_deluge

- name: "---[INSTALL]--- Cherrytree"
  import_tasks: cherrytree/cherrytree.yml
  when: install_cherrytree
  tags:
    - extra_software
    - install_cherrytree
    - install_editors

- name: "---[INSTALL]--- Kubectl"
  import_tasks: kubectl/kubectl.yml
  when: install_kubectl
  tags:
    - extra_software
    - install_kubectl
    - ohermosa

- name: "---[INSTALL]--- MEGAcmd"
  import_tasks: megacmd/megacmd.yml
  when: install_megacmd
  tags:
    - extra_software
    - install_megacmd
    - ohermosa

- name: "---[INSTALL]--- MEGAsync"
  import_tasks: megasync/megasync.yml
  when: install_megasync
  tags:
    - extra_software
    - install_megasync
    - install_mega

- name: "---[INSTALL]--- Vivaldi"
  import_tasks: vivaldi/vivaldi.yml
  when: install_vivaldi
  tags:
    - extra_software
    - install_vivaldi
