---

- include_vars:
    file: "{{ item }}"
  loop:
    - "{{ linux_distribution }}.yml"
    - "{{ ansible_user }}.yml"
  ignore_errors: true
  tags:
    - always

- name: "---[INSTALL]--- flatpak"
  import_tasks: flatpak.yml
  when:
    - linux_distribution == "fedora"
    - install_flatpak
  tags:
    - extra_software
    - flatpak
    - telegram
    - slack
    - pycharm
    - postman
    - skype
    - franz

- name: "---[INSTALL]--- docker"
  import_tasks: docker/docker.yml
  when: install_docker
  tags:
    - extra_software
    - docker

- name: "---[INSTALL]--- dropbox"
  import_tasks: dropbox/dropbox.yml
  when: install_dropbox
  tags:
    - extra_software
    - dropbox

- name: "---[INSTALL]--- Visual Studio Code"
  import_tasks: code/code.yml
  when: install_code
  tags:
    - extra_software
    - code
    - editors

- name: "---[INSTALL]--- Spotify"
  import_tasks: spotify/spotify.yml
  when: install_spotify
  tags:
    - extra_software
    - spotify

- name: "---[INSTALL]--- Oh My ZSH!"
  import_tasks: oh_my_zsh.yml
  when:
    - install_ohmyzsh
  tags:
    - extra_software
    - ohmyzsh

- name: "---[INSTALL]--- Sublime Text"
  import_tasks: sublime/sublime.yml
  when: install_sublime
  tags:
    - extra_software
    - sublime
    - editors

- name: "---[INSTALL]--- Atom"
  import_tasks: atom/atom.yml
  when: install_atom
  tags:
    - extra_software
    - atom
    - editors

- name: "---[INSTALL]--- Gitkraken"
  import_tasks: gitkraken/gitkraken.yml
  when: install_gitkraken
  tags:
    - extra_software
    - gitkraken

- name: "---[INSTALL]--- Telegram"
  import_tasks: telegram/telegram.yml
  when: install_telegram
  tags:
    - extra_software
    - telegram
    - socials

- name: "---[INSTALL]--- Slack"
  import_tasks: slack/slack.yml
  when: install_slack
  tags:
    - extra_software
    - slack
    - socials

- name: "---[INSTALL]--- Forticlient VPN"
  import_tasks: forticlientvpn/forticlientvpn.yml
  when: install_forticlientvpn
  tags:
    - extra_software
    - forticlientvpn
    - vpnclient

- name: "---[INSTALL]--- TLP"
  import_tasks: tlp/tlp.yml
  when: install_tlp
  tags:
    - extra_software
    - tlp

- name: "---[INSTALL]--- Virtualbox"
  import_tasks: virtualbox/virtualbox.yml
  when: install_virtualbox
  tags:
    - extra_software
    - virtualbox

- name: "---[INSTALL]--- PyCharm"
  import_tasks: pycharm/pycharm.yml
  when: install_pycharm
  tags:
    - extra_software
    - pycharm
    - editors

- name: "---[INSTALL]--- Keepass"
  import_tasks: keepass/keepass.yml
  when: install_keepass
  tags:
    - extra_software
    - keepass
    - pass_managers

- name: "---[INSTALL]--- Buttercup"
  import_tasks: buttercup/buttercup.yml
  when: install_buttercup
  tags:
    - extra_software
    - buttercup
    - pass_managers

- name: "---[INSTALL]--- Windscribe client"
  import_tasks: windscribe/windscribe.yml
  when: install_windscribe
  tags:
    - extra_software
    - windscribe
    - vpnclient

- name: "---[INSTALL]--- Google Chrome"
  import_tasks: chrome/chrome.yml
  when: install_chrome
  tags:
    - extra_software
    - chrome
    - browsers

- name: "---[INSTALL]--- Teamviewer"
  import_tasks: teamviewer/teamviewer.yml
  when: install_teamviewer
  tags:
    - extra_software
    - teamviewer

- name: "---[INSTALL]--- No Machine"
  import_tasks: nomachine/nomachine.yml
  when: install_nomachine
  tags:
    - extra_software
    - nomachine
    - remotes

- name: "---[INSTALL]--- Ether Cloud Services Client"
  import_tasks: ecs.yml
  when: install_ecs
  tags:
    - extra_software
    - ecs

- name: "---[INSTALL]--- Postman"
  import_tasks: postman/postman.yml
  when: install_postman
  tags:
    - extra_software
    - postman

- name: "---[INSTALL]--- Skype"
  import_tasks: skype/skype.yml
  when: install_skype
  tags:
    - extra_software
    - skype

- name: "---[INSTALL]--- Java"
  import_tasks: java/java.yml
  when: install_java
  tags:
    - extra_software
    - java
    - apachedirectory

- name: "---[INSTALL]--- Apache Directory"
  block:
    - import_tasks: apachedirectory.yml
      when:
        - install_apachedirectory
        - linux_distribution != "arch"

    - name: "[ARCH] Install apache directory studio"
      become: false
      yay:
        name: "{{ apachedirectory_package }}"
        state: present
        update_cache: true
      when:
        - install_apachedirectory
        - linux_distribution == "arch"
  tags:
    - extra_software
    - apachedirectory

- name: "---[INSTALL]--- Rambox"
  import_tasks: rambox/rambox.yml
  when: install_rambox
  tags:
    - extra_software
    - rambox

- name: "---[INSTALL]--- Franz"
  import_tasks: franz/franz.yml
  when: install_franz
  tags:
    - extra_software
    - franz

- name: "---[INSTALL]--- Chromium Browser"
  import_tasks: chromium/chromium.yml
  when: install_chromium
  tags:
    - extra_software
    - chromium
    - browsers

- name: "---[INSTALL]--- Deluge"
  import_tasks: deluge/deluge.yml
  when:
    - install_deluge
    - desktop_environment == "gnome"
  tags:
    - extra_software
    - deluge

- name: "---[INSTALL]--- Cherrytree"
  import_tasks: cherrytree/cherrytree.yml
  when: install_cherrytree
  tags:
    - extra_software
    - cherrytree
    - editors

- name: "---[INSTALL]--- Kubectl"
  import_tasks: kubectl/kubectl.yml
  when: install_kubectl
  tags:
    - extra_software
    - kubectl

- name: "---[INSTALL]--- MEGAcmd"
  import_tasks: megacmd/megacmd.yml
  when: install_megacmd
  tags:
    - extra_software
    - megacmd
    - mega

- name: "---[INSTALL]--- MEGAsync"
  import_tasks: megasync/megasync.yml
  when: install_megasync
  tags:
    - extra_software
    - megasync
    - mega

- name: "---[INSTALL]--- Vivaldi"
  import_tasks: vivaldi/vivaldi.yml
  when: install_vivaldi
  tags:
    - extra_software
    - vivaldi
    - browsers

- name: "---[INSTALL]--- Brave"
  import_tasks: brave/brave.yml
  when: install_brave
  tags:
    - extra_software
    - brave
    - browsers

- name: "---[INSTALL]--- Bitwarden"
  import_tasks: bitwarden/bitwarden.yml
  when: install_bitwarden
  tags:
    - extra_software
    - bitwarden
    - pass_managers

- name: "---[INSTALL]--- Lexnet"
  import_tasks: lexnet.yml
  when:
    - install_lexnet
    - linux_distribution == "ubuntu"
  tags:
    - extra_software
    - lexnet

- name: "---[INSTALL]--- Pass"
  import_tasks: pass/pass.yml
  when: install_pass
  tags:
    - extra_software
    - pass
    - pass_managers

- name: "---[INSTALL]--- Bucklespring"
  import_tasks: bucklespring.yml
  when:
    - linux_distribution == "ubuntu" or linux_distribution == "debian"
    - install_bucklespring
  tags:
    - extra_software
    - bucklespring

- name: "---[INSTALL]--- ProtonVPN"
  import_tasks: protonvpn.yml
  when: install_protonvpn
  tags:
    - extra_software
    - protonvpn

- name: "---[INSTALL]--- Prezto"
  import_tasks: prezto.yml
  when: install_prezto
  tags:
    - extra_software
    - prezto

- name: "---[INSTALL]--- Etcher"
  import_tasks: etcher.yml
  when: install_etcher
  tags:
    - extra_software
    - etcher

- name: "---[INSTALL]--- WoeUSB"
  import_tasks: woeusb/woeusb.yml
  when: install_woeusb
  tags:
    - extra_software
    - woeusb

- name: "---[INSTALL]--- GO"
  import_tasks: go.yml
  when: install_go
  tags:
    - extra_software
    - go

- name: "---[INSTALL]--- FZF"
  import_tasks: fzf.yml
  when: install_fzf
  tags:
    - extra_software
    - fzf

- name: "---[INSTALL]--- VIM PLUGINS"
  import_tasks: vim_plugins.yml
  when: install_vimplugins
  tags:
    - extra_software
    - vim
    - vimplugins

- name: "---[INSTALL]--- AUTHY"
  import_tasks: authy/authy.yml
  when: install_authy
  tags:
    - extra_software
    - authy

- name: "---[INSTALL]--- YAKYAK"
  import_tasks: yakyak/yakyak.yml
  when: install_yakyak
  tags:
    - extra_software
    - yakyak

- name: "---[INSTALL]--- HIRI"
  import_tasks: hiri/hiri.yml
  when: install_hiri
  tags:
    - extra_software
    - hiri

- name: "---[INSTALL]--- STEAM"
  import_tasks: steam.yml
  when:
    - install_steam
    - linux_distribution == "ubuntu"
  tags:
    - extra_software
    - steam

- name: "---[INSTALL]--- WIREGUARD"
  import_tasks: wireguard/wireguard.yml
  when:
    - install_wireguard
  tags:
    - extra_software
    - wireguard
