---

- name: "Install Docker"
  import_tasks:
    name: docker.yml

- name: "Install Dropbox"
  import_tasks:
    name: dropbox.yml

- name: "Install Visual Studio Code"
  import_tasks:
    name: vscode.yml

- name: "Install Spotify"
  import_tasks:
    name: spotify.yml

- name: "Install Oh My ZSH!"
  import_tasks:
    name: oh_my_zsh.yml
