---

- name: "Install Dropbox"
  import_tasks:
    name: dropbox.yml

- name: "Install code"
  import_tasks:
    name: vscode.yml

- name: "Install Spotify"
  import_tasks:
    name: spotify.yml

- name: "Install Oh My ZSH!"
  import_tasks:
    name: oh_my_zsh.yml
