---

- name: "[DOCKER] Create user config directory"
  file:
    path: "/home/{{ ansible_user }}/.docker"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "[DOCKER] create config.json"
  copy:
    content: "{{ docker_config_json | to_json }}"
    dest: "/home/{{ ansible_user }}/.docker/config.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: "[DOCKER] create daemon.json"
  copy:
    content: "{{ docker_daemon_json | to_json }}"
    dest: /etc/docker/daemon.json

- name: "[DOCKER] Restart docker"
  systemd:
    name: docker
    state: restarted
  become: true
  become_method: sudo
