---

- name: "Configure VIM editor"
  import_tasks: vim.yml

- name: "Configure /etc/profile"
  become: true
  become_method: sudo
  block:
    - lineinfile:
        path: /etc/profile
        line: 'export VAULT_TOKEN=$(secret-tool lookup vault_sistemas TOKEN)'
      when: desktop_environment != 'kde'

    - lineinfile:
        path: /etc/profile
        line: 'export VAULT_TOKEN=$(kwalletcli -f Passwords -e TOKEN)'
      when: desktop_environment == 'kde'

- name: "Delete bash files"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/.bashrc"
    - "{{ ansible_user_dir }}/.bash_history"
    - "{{ ansible_user_dir }}/.zshrc"
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.vault_pass*txt"
    - "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes"

- name: "create vault_pass files"
  lineinfile:
    path: "{{ ansible_user_dir}}/{{ item.name }}"
    line: "{{ item.content }}"
  no_log: true
  loop:
    - name: .vault_pass_personal.txt
      content: "{{ vault_personal_pass }}"
    - name: .vault_pass_datio.txt
      content: "{{ vault_datio_pass }}"

- name: "create link to vault_pass file"
  file:
    src: "{{ ansible_user_dir }}/.vault_pass_datio.txt"
    dest: "{{ ansible_user_dir }}/.vault_pass.txt"
    state: link

- name: "Configure environment"
  block:
    - name: "Wait until dropbox files exist"
      wait_for:
        path: "{{ item.src }}"
        timeout: "{{ wait_dropbox_sync }}"
      loop: "{{ links_to_create }}"

    - name: "delete zsh configuration files"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ ansible_user_dir }}/.oh-my-zsh"
        - "{{ ansible_user_dir }}/.zshrc"
        - "{{ ansible_user_dir }}/.zprezto"

    - name: "Create links from Dropbox"
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ links_to_create }}"

    - name: "find files in {{ ansible_user_dir }}/.ssh"
      find:
        paths: "{{ ansible_user_dir }}/.ssh/"
        recurse: true
        file_type: file
      register: find_response

    - name: "change permissions to files"
      vars:
        id_query: "[].path"
      file:
        dest: "{{ item }}"
        mode: 0600
      loop: "{{ find_response.files | json_query(id_query) }}"

    - name: "find prezto config files"
      find:
        paths: "{{ dropbox_dir }}/backups/zprezto/runcoms"
        patterns: "^(?!README).*$"
        use_regex: true
        file_type: file
      register: find_response

    - name: "create links to config files"
      vars:
        id_query: "[].path"
      file:
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/.{{ item | basename }}"
        state: link
      loop: "{{ find_response.files | json_query(id_query) }}"

- name: "copy powerline truetype fonts"
  vars:
    font_dir: "{{ ansible_user_dir }}/.local/share/fonts"
  block:
    - name: "create {{ font_dir }}"
      file:
        path: "{{ font_dir }}"
        state: directory

    - name: "copy fonts"
      copy:
        src: "NerdFonts/*ttf"
        dest: "{{ ansible_user_dir }}/.local/share/fonts"

    - name: "refresh font cache"
      shell: fc-cache -f {{ font_dir }}"
