---

- name: "Create python-venv directory"
  file:
    path: "{{ ansible_user_dir }}/python-venv"
    state: directory

- name: "Delete bash files"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/.bashrc"
    - "{{ ansible_user_dir }}/.bash_history"
    - "{{ ansible_user_dir }}/.zshrc"
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.vault_pass*txt"
    - "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes"

- name: "create empty vault_pass files"
  file:
    path: "{{ ansible_user_dir}}/{{ item }}"
    state: touch
  loop:
    - .vault_pass_personal.txt
    - .vault_pass_datio.txt

- name: "create link to vault_pass file"
  file:
    src: "{{ ansible_user_dir }}/.vault_pass_datio.txt"
    dest: "{{ ansible_user_dir }}/.vault_pass.txt"
    state: link

- name: "create python-venv directory"
  file:
    path: "{{ ansible_user_dir }}/python-venv"
    state: directory

- name: "Configure environment"
  block:
    - name: "Wait until dropbox files exist"
      wait_for:
        path: "{{ item.src }}"
        timeout: "{{ wait_dropbox_sync }}"
      loop: "{{ links_to_create }}"

    - name: "Create links from Dropbox"
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ links_to_create }}"

    - name: "find files in {{ ansible_user_dir }}/.ssh"
      find:
        recurse: true
        file_type: file
        paths: "{{ ansible_user_dir }}/.ssh/"
      register: find_response

    - name: "change permissions to files"
      vars:
        id_query: "[].path"
      file:
        dest: "{{ item }}"
        mode: 0600
      loop: "{{ find_response.files | json_query(id_query) }}"

    - name: "Create link to Oh my zsh! theme directory in Dropbox"
      file:
        src: "{{ dropbox_dir }}/backups/oh-my-zsh_custom_themes"
        dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes"
        state: link
