---

- name: "Create python-venv directory"
  file:
    path: "{{ ansible_user_dir }}/python-venv"
    state: directory

- name: "Delete bash files"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/.bashrc"
    - "{{ ansible_user_dir }}/.bash_history"
    - "{{ ansible_user_dir }}/.zshrc"
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.vault_pass*txt"
    - "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes"

- name: "create empty vault_pass files"
  file:
    path: "{{ ansible_user_dir}}/{{ item }}"
    state: touch
  loop:
    - .vault_pass_personal.txt
    - .vault_pass_datio.txt

- name: "create link to vault_pass file"
  file:
    src: "{{ ansible_user_dir }}/.vault_pass_datio.txt"
    dest: "{{ ansible_user_dir }}/.vault_pass.txt"
    state: link

- name: "create python-venv directory"
  file:
    path: "{{ ansible_user_dir }}/python-venv"
    state: directory

- name: "Configure environment"
  block:
    - name: "Create links from Dropbox"
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ links_to_create }}"

    - name: "Change permissions to files in .ssh"
      file:
        dest: "{{ ansible_user_dir }}/.ssh/*"
        mode: 0600

    - name: "Create link to Oh my zsh! theme directory in Dropbox"
      file:
        src: "{{ dropbox_dir }}/backups/oh-my-zsh_custom_themes"
        dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes"
        state: link
