---

- name: "Wait until private ssh key exists"
  wait_for:
    path: "/home/{{ ansible_user }}/.ssh/id_rsa"
    timeout: "{{ wait_dropbox_sync }}"

- name: "Create {{ git_dir }}"
  file:
    path: "{{ git_dir }}"
    state: directory

- name: "Clone git repositories"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest}}"
    clone: yes
    key_file: "/home/{{ ansible_user }}/.ssh/id_rsa"
    accept_hostkey: true
  with_items:
    - "{{ git_repositories.work }}"
    - "{{ git_repositories.home }}"
  ignore_errors: true
  tags:
    - clone_repos

- name: "Create remotes for repositories"
  block:
    # create remotes for repositories copied in other platforms

    - name: "Create github repositories for WORK"
      include_role:
        name: tools/github_repo
      vars:
        github_token: "{{ github_token_access }}"
        repo_name: "{{ (item.repo | basename).split('.')[0] }}"
        repo_private: true
        repo_state: present
      when:
        - item.remote is defined
        - item.remote == "github"
      with_items: "{{ git_repositories.work }}"

    - name: "Create gitlab repositories for WORK"
      include_role:
        name: tools/gitlab_repo
      vars:
        gitlab_token: "{{ gitlab_token_access }}"
        repo_name: "{{ (item.repo | basename).split('.')[0] }}"
        visibility: private
        repo_state: present
      when:
        - item.remote is defined
        - item.remote == "gitlab"
      with_items: "{{ git_repositories.work }}"

    - name: "Create new remote for work repositories"
      shell: "git remote add {{ item.remote }} {{ remote_url }}"
      args:
        chdir: "{{ item.dest }}"
      with_items: "{{ git_repositories.work }}"
      when: item.remote is defined
      register: remote_response
      failed_when: false
      vars:
        remote_url: "git@{{ item.remote }}.com:ohermosa/{{ (item.repo | basename).split('.')[0] }}.git"

    - name: "Create github repositories for HOME"
      include_role:
        name: tools/github_repo
      vars:
        github_token: "{{ github_token_access }}"
        repo_name: "{{ (item.repo | basename).split('.')[0] }}"
        repo_private: true
        repo_state: present
      when:
        - item.remote is defined
        - item.remote == "github"
      with_items: "{{ git_repositories.home }}"

    - name: "Create gitlab repositories for HOME"
      include_role:
        name: tools/gitlab_repo
      vars:
        gitlab_token: "{{ gitlab_token_access }}"
        repo_name: "{{ (item.repo | basename).split('.')[0] }}"
        repo_private: private
        repo_state: present
      when:
        - item.remote is defined
        - item.remote == "gitlab"
      with_items: "{{ git_repositories.home }}"

    - name: "Create new remote for home repositories"
      shell: "git remote add {{ item.remote }} {{ remote_url }}"
      args:
        chdir: "{{ item.dest }}"
      with_items: "{{ git_repositories.home }}"
      when: item.remote is defined
      register: remote_response
      failed_when: false
      vars:
        remote_url: "git@{{ item.remote }}.com:ohermosa/{{ (item.repo | basename).split('.')[0] }}.git"

    # Create remotes for repositories that have forks

    - name: "get repositories to check if have forks"
      set_fact:
        repos_to_check: "{{ repos_to_check | default([]) | union([repository_name]) }}"
      with_items: "{{ git_repositories.home }}"
      when:
        - item.forks is defined
        - item.forks | bool
      vars:
        repository_name: "{{ (item.repo | basename).split('.')[0] }}"

    - debug: var=repos_to_check

    - gitlab_get_forks:
        gitlab_auth_key: "{{ gitlab_token_access }}"
        name: "{{ item }}"
      loop: "{{ repos_to_check }}"
      register: forks_response

    - debug:
        msg: "{{ forks_response | json_query('results[].forks[]') }}"

    - shell: "git remote add {{ item.user }} {{ item.remote }}"
      args:
        chdir: "{{ git_dir }}/{{ repo_name }}"
      loop: "{{ forks_response | json_query('results[].forks[]') }}"
      vars:
        repo_name: "{{ (item.remote | basename).split('.')[0] }}"
  tags:
    - create_remotes


- name: "Configure name and user of BBVA repositories"
  git_config:
    name: user.name
    repo: "{{ item }}"
    scope: local
    value: "{{ git_user_name }}"
  loop: "{{ git_repositories.work | json_query('[].dest') }}"

- name: "Configure name and user of BBVA repositories"
  git_config:
    name: user.email
    repo: "{{ item }}"
    scope: local
    value: "{{ git_user_mail_work }}"
  loop: "{{ git_repositories.work | json_query('[].dest') }}"

- name: "Configure name and user of personal repositories"
  git_config:
    name: user.name
    repo: "{{ item }}"
    scope: local
    value: "{{ git_user_name }}"
  loop: "{{ git_repositories.home | json_query('[].dest') }}"

- name: "Configure name and user of personal repositories"
  git_config:
    name: user.email
    repo: "{{ item }}"
    scope: local
    value: "{{ git_user_mail_personal}}"
  loop: "{{ git_repositories.home | json_query('[].dest') }}"
