---

- name: "Wait until file exist in Dropbox"
  wait_for:
    path: "{{ dropbox_dir }}/datio/gnome_config"
    timeout: "{{ wait_dropbox_sync }}"

- name: "Parse dconf dump for general"
  dconf_to_list:
    paths_to_restore: "{{ dconf_paths_to_restore_general }}"
    dconf_file: "{{ dropbox_dir }}/datio/gnome_config"
  register: response_general

- name: "Import gnome general config"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ response_general.message }}"
  when: restore_path | default("") in item.key

- name: "Parse dconf dump for ubuntu"
  dconf_to_list:
    paths_to_restore: "{{ dconf_paths_to_restore_gnome }}"
    dconf_file: "{{ dropbox_dir }}/datio/gnome_config"
  register: response_gnome
  when: desktop_environment == "gnome"

- name: "Import ubuntu gnome config"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ response_gnome.message }}"
  when:
    - (desktop_environment == "gnome") or (restore_path | default("") in item.key)
