---

- name: "[GO] check if $GOPATH exists"
  stat:
    path: "{{ ansible_user_dir }}/go"
  register: gopath_response

- name: "[GO] create $GOPATH"
  file:
    path: "{{ ansible_user_dir }}/go"
    state: directory
  when: not gopath_response.stat.exists

- name: "[GO] download go packages"
  shell: "go get {{ item }}"
  loop: "{{ go_packages }}"
  environment:
    GOPATH: "{{ ansible_user_dir }}/go"
