---

- name: "Import gpg keys from keyserver"
  shell: "gpg --keyserver {{ gpg_keyserver }} --recv-keys  {{ item }}"
  changed_when: "'sin cambios' not in gpg_response.stderr"
  register: gpg_response
  loop: "{{ gpg_pub_keys }}"

- name: "Get GPG keys"
  shell: "gpg -k"
  register: gpg_response

- debug:
    msg: "{{ gpg_response.stdout }}"
