---

- name: "[KDE] search kde config files not backed up yet"
  find:
    path: "{{ ansible_user_dir }}/.config"
    use_regex: true
    pattern: "^.*rc$"
    file_type: file
  register: find_response

- name: "[KDE] backing up KDE config"
  vars:
    id_query: "[].path"
  copy:
    remote_src: true
    src: "{{ item }}"
    dest: "{{ kde_backup_dir }}/{{ item | basename }}"
  loop: "{{ find_response.files | json_query(id_query) }}"
