---

- name: "Configure /etc/hosts"
  become: true
  become_method: sudo
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }}\t{{ item.host }}"
  loop: "{{ etc_hosts }}"
  tags:
    - post_install
    - post_resolv
    - ohermosa

- name: "create secrets"
  import_tasks: secrets.yml
  tags:
    - post_install
    - post_secrets
    - ohermosa

- name: "configure megacmd client"
  import_tasks: megacmd.yml
  tags:
    - post_install
    - post_megacmd

- name: "Customize firefox"
  import_tasks: firefox.yml
  tags:
    - post_install
    - post_firefox
    - ohermosa

- name: "Delete default directories in /home/{{ ansible_user }}"
  file:
    path: "/home/{{ ansible_user }}/{{ item }}"
    state: absent
  loop:
    - Documentos
    - Imágenes
    - Libros
    - Música
    - Plantillas
    - Público
    - Vídeos
  tags:
    - post_install
    - post_del_default_dirs
    - ohermosa

- import_tasks: kde_restore.yml
  when: desktop_environment == "kde"
  tags:
    - post_install
    - post_kde_restore

- import_tasks: kde_backup.yml
  when: desktop_environment == "kde"
  tags:
    - pre_kde_backup

- import_tasks: gnome_extensions.yml
  when: desktop_environment == "gnome"
  tags:
    - post_install
    - post_gnome_extensions
    - post_gnome

- import_tasks: gnome_conf.yml
  when: desktop_environment == "gnome"
  tags:
    - post_install
    - post_gnome_conf
    - post_gnome

- import_tasks: docker.yml
  tags:
    - post_install
    - post_docker
    - ohermosa

- import_tasks: crontab.yml
  tags:
    - post_install
    - post_crontab

- import_tasks: environment.yml
  tags:
    - post_install
    - post_environment
    - ohermosa

- import_tasks: git.yml
  tags:
    - post_install
    - post_git
    - ohermosa

- import_tasks: sublime.yml
  tags:
    - post_install
    - post_sublime

- import_tasks: network.yml
  become: true
  become_method: sudo
  tags:
    - post_install
    - post_network

- import_tasks: gpg.yml
  tags:
    - post_install
    - post_gpg
    - ohermosa
