---

- name: "Configure /etc/hosts"
  become: true
  become_method: sudo
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }}\t{{ item.host }}"
  loop: "{{ etc_hosts }}"
  tags:
    - post_install
    - post_resolv
    - ohermosa

- name: "create secrets"
  import_tasks: secrets.yml
  tags:
    - post_install
    - post_secrets
    - ohermosa

- name: "configure megacmd client"
  import_tasks: megacmd.yml
  tags:
    - post_install
    - post_megacmd
    - ohermosa

- name: "Customize firefox"
  import_tasks: firefox.yml
  tags:
    - post_install
    - post_firefox
    - ohermosa

- name: "Delete default directories in /home/{{ ansible_user }}"
  file:
    path: "/home/{{ ansible_user }}/{{ item }}"
    state: absent
  loop:
    - Documentos
    - Imágenes
    - Libros
    - Música
    - Plantillas
    - Público
    - Vídeos
  tags:
    - post_install
    - post_del_default_dirs
    - ohermosa

- import_tasks: kde_restore.yml
  when: desktop_environment == "kde"
  tags:
    - post_install
    - post_kde_restore
    - ohermosa

- import_tasks: gnome_extensions.yml
  when: desktop_environment == "gnome"
  tags:
    - post_install
    - post_gnome_extensions
    - post_gnome
    - ohermosa

- import_tasks: gnome_conf.yml
  when: desktop_environment == "gnome" or desktop_environment == "cinnamon"
  tags:
    - post_install
    - post_gnome_conf
    - post_gnome
    - ohermosa

- import_tasks: docker.yml
  tags:
    - post_install
    - post_docker
    - ohermosa

- import_tasks: crontab.yml
  tags:
    - post_install
    - post_crontab

- import_tasks: environment.yml
  tags:
    - post_install
    - post_environment
    - post_env
    - ohermosa

- import_tasks: git.yml
  tags:
    - post_install
    - post_git
    - ohermosa

- import_tasks: python.yml
  tags:
    - post_install
    - post_git
    - post_python
    - ohermosa

- import_tasks: sublime.yml
  tags:
    - post_install
    - post_sublime

- import_tasks: network.yml
  become: true
  become_method: sudo
  tags:
    - post_install
    - post_network
    - ohermosa

- import_tasks: gpg.yml
  tags:
    - post_install
    - post_gpg
    - post_pass
    - ohermosa

- name: "Configure VIM"
  import_tasks: vim.yml
  tags:
    - post_install
    - post_vim
    - ohermosa

- name: "Configure Gimp"
  import_tasks: gimp.yml
  tags:
    - post_install
    - post_gimp
    - ohermosa

- name: "install HP packages"
  import_tasks: hp.yml
  tags:
    - post_install
    - post_hp
    - ohermosa

- name: "configure pass secrets manager"
  import_tasks: pass.yml
  tags:
    - post_install
    - post_pass
    - ohermosa

- name: "configure prezto"
  import_tasks: prezto.yml
  tags:
    - post_install
    - post_prezto
    - ohermosa

- name: "configure spotify tui"
  import_tasks: spotify.yml
  tags:
    - post_install
    - post_spotify
    - ohermosa
