---

- name: "configure sublime"
  import_tasks: sublime.yml
  when: use_dropbox
  tags:
    - post_install
    - sublime
    - sublimetext
    - sublimemerge
    - post_sublime
    - post_sublimetext
    - post_sublimemerge

- name: "configure VPNs"
  import_tasks: network.yml
  become: true
  become_method: sudo
  when: use_dropxbox | default(true)
  tags:
    - post_install
    - network

- name: "import GPG keys"
  import_tasks: gpg.yml
  tags:
    - post_install
    - gpg
    - pass

- name: "Configure VIM"
  import_tasks: vim.yml
  tags:
    - post_install
    - vim
    - vimplugins
    - post_vim
    - post_vimplugins

- name: "Configure Gimp"
  import_tasks: gimp.yml
  tags:
    - post_install
    - gimp

- name: "install HP packages"
  import_tasks: hp.yml
  tags:
    - post_install
    - hp

- name: "configure pass secrets manager"
  import_tasks: pass.yml
  tags:
    - post_install
    - pass
    - post_pass

- name: "configure spotify tui"
  import_tasks: spotify.yml
  tags:
    - post_install
    - spotify
    - post_spotify

- name: "configure user photo"
  import_tasks: user.yml
  tags:
    - post_install
    - user
    - post_user

- name: "configure Zeal"
  import_tasks: zeal.yml
  tags:
    - post_install
    - zeal
    - post_zeal

- name: "configure github CLI"
  import_tasks: github_cli.yml
  tags:
    - post_install
    - githubcli
    - post_githubcli

- name: "configure Oracle Cloud"
  import_tasks: oracle_cloud.yml
  tags:
    - post_install
    - oracle_cloud
    - post_oracle_cloud
