---

- name: "Copy vpn configurations files to NetworkManager"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
    owner: root
    group: root
  no_log: true
  loop:
    - src: bbva_vpn.j2
      dest: /etc/NetworkManager/system-connections/BBVA
    - src: datio_mx_vpn.j2
      dest: /etc/NetworkManager/system-connections/Datio_CCR
