---

- name: "Creating secrets"
  shell: >
    secret-tool store
    --label='{{ item.label }}'
    '{{ item.secret_key }}' '{{ item.secret_value }}'
  args:
    stdin: "{{ item.secret }}"
    stdin_add_newline: false
  loop: "{{ secrets }}"
