---

- name: "[VIM] Configure VIM editor"
  lineinfile:
    path: "{{ ansible_user_dir }}/.vimrc"
    line: "{{ item }}"
    state: present
    create: true
  loop: "{{ vim_config }}"

- name: "[VIM] copy ftplugin directory"
  copy:
    src: ftplugin
    dest: "{{ ansible_user_dir }}/.vim/"
