---

- include_tasks: "code_{{ linux_distribution }}.yml"

- block:
    - name: "get json with extensions"
      uri:
        url: "{{ code_extensions_url }}"
      register: extensions_response

    - name: "Install extensions for Visual Studio Code"
      become: false
      become_user: "{{ ansible_user }}"
      vars:
        id_query: "[].metadata.publisherId"
      shell: "code --install-extension {{ item }}"
      loop: "{{ extensions_response.json | default([]) | json_query(id_query) | list }}"
  tags:
    - code_extensions
