---

- include_tasks: "code_{{ linux_distribution }}.yml"

- name: "Install 'Sync settings' for Visual Studio Code"
  become: false
  become_user: "{{ ansible_user }}"
  shell: code --install-extension shan.code-settings-sync
