---

- include_tasks: "code_{{ linux_distribution }}.yml"

- block:
    - name: "get json with extensions"
      uri:
        url: "{{ code_extensions_urls }}"
      register: extensions_response

    - name: "get list of extensions"
      set_fact:
        extensions: "{{ extensions_response.json | json_query(id_query) | map('lower') | list }}"
      vars:
        id_query: "[].metadata.publisherId"

    - name: "Install extensions for Visual Studio Code"
      become: false
      become_user: "{{ ansible_user }}"
      shell: "code --install-extension {{ item }}"
      loop: "{{ extensions }}"
  tags:
    - code_extensions
