---

- name: "Create user config directory"
  file:
    path: "/home/{{ ansible_user_id }}/.docker"
    state: present
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: "Create link to config.json"
  become_user: "{{ ansible_user_id }}"
  file:
    src: "{{ dropbox_dir }}/docker.config.json"
    dest: "/home/{{ ansible_user_id }}/.docker/config.json"
    state: link
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: "Create link for docker daemon.json"
  file:
    src: "{{ dropbox_dir }}/datio/etc.docker.daemon.json"
    dest: /etc/docker/daemon.json
    state: link
  become: true
  become_method: sudo

- name: "Restart docker"
  systemd:
    name: docker
    state: restarted
  become: true
  become_method: sudo
