---

- name: "Create python-venv directory"
  file:
    path: "{{ ansible_user_dir }}/python-venv"
    state: directory

- name: "Delete bash files"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/.bashrc"
    - "{{ ansible_user_dir }}/.bash_history"
    - "{{ ansible_user_dir }}/.zshrc"
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes"
    - "{{ ansible_user_dir }}/.vault_pass*txt"

- name: "create empty vault_pass files"
  file:
    path: "{{ item }}"
    state: touch
  loop:
    - .vault_pass_personal.txt
    - .vault_pass_datio.txt

- name: "create link to vault_pass file"
  file:
    src: .vault_pass_datio.txt
    dest: .vault_pass.txt
    state: link

- name: "Configure environment"
  block:
    - name: "Create links from Dropbox"
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ links_to_create }}"

    - name: "Change permissions to files in .ssh"
      file:
        path: "{{ item }}"
        mode: 0600
      with_items:
        - "/home/{{ ansible_user }}/.ssh/config"
        - "/home/{{ ansible_user }}/.ssh/id_rsa"
        - "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
        - "/home/{{ ansible_user }}/.ssh/id_bbva"

    - name: "Change permissions to files in .ssh directories"
      file:
        path: "{{ item }}/*"
        mode: 0600
      with_items:
        - "/home/{{ ansible_user }}/.ssh/ccr"
        - "/home/{{ ansible_user }}/.ssh/aws"
        - "/home/{{ ansible_user }}/.ssh/isilon"

    - name: "Create link to Oh my zsh! theme directory in Dropbox"
      file:
        src: "{{ dropbox_dir }}/backups/oh-my-zsh_custom_themes"
        dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/themes"
        state: link
