---

- name: "Create python-venv directory"
  file:
    path: "{{ ansible_user_dir }}/python-venv"
    state: directory

- name: "Delete bash files"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/home/{{ ansible_user }}/.bashrc"
    - "/home/{{ ansible_user }}/.bash_history"
    - "/home/{{ ansible_user }}/.zshrc"
    - "/home/{{ ansible_user }}/.ssh"
    - "/home/{{ ansible_user }}/.oh-my-zsh/custom/themes"

- name: "Configure environment"
  block:
    - name: "Create links from Dropbox"
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ links_to_create }}"

    - name: "Change permissions to files in .ssh"
      file:
        path: "{{ item }}"
        mode: 0600
      with_items:
        - "/home/{{ ansible_user }}/.ssh/config"
        - "/home/{{ ansible_user }}/.ssh/id_rsa"
        - "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
        - "/home/{{ ansible_user }}/.ssh/id_bbva"

    - name: "Change permissions to files in .ssh directories"
      file:
        path: "{{ item }}/*"
        mode: 0600
      with_items:
        - "/home/{{ ansible_user }}/.ssh/ccr"
        - "/home/{{ ansible_user }}/.ssh/aws"
        - "/home/{{ ansible_user }}/.ssh/isilon"

    - name: "Create link to Oh my zsh! theme directory in Dropbox"
      file:
        src: "{{ dropbox_dir }}/backups/oh-my-zsh_custom_themes"
        dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/themes"
        state: link
