---

- name: "[UBUNTU] Install several theme packages"
  apt:
    name:
      - arc-theme
      - elementary-icon-theme
      - papirus-icon-theme
      - gnome-tweaks
      - python-psutil
      - python3-psutil
    state: latest
    update_cache: true
  when: linux_distribution == "ubuntu"

- name: "[FEDORA] Install several theme packages"
  yum:
    name:
      - arc-theme
      - elementary-icon-theme
      - papirus-icon-theme
      - gnome-tweaks
      - python2-psutil
      - python3-psutil
    state: latest
    update_cache: true
  when: linux_distribution == "fedora"
