---

- name: "Parse dconf dump"
  dconf_to_list:
    paths_to_restore: "{{ dconf_paths_to_restore }}"
    dconf_file: "{{ dropbox_dir }}/datio/gnome_config"
  register: response

- name: "Import gnome config"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ response.message }}"

- name: "Create temporal directory"
  file:
    path: "/tmp/gnome_extensions"
    state: directory

- include_tasks: install_gnome_extension.yml
  loop: "{{ gnome_extensions }}"

- name: "Delete temporal directory"
  file:
    path: "/tmp/gnome_extensions"
    state: absent
