---

- name: "Parse dconf dump"
  dconf_to_list:
    paths_to_restore: "{{ dconf_paths_to_restore }}"
    dconf_file: "{{ dropbox_dir }}/datio/gnome_config"
  register: response

- name: "Import gnome config"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ response.message }}"
