---

- import_tasks: gnome_packages.yml
  when: "'GNOME' in ansible_env.XDG_CURRENT_DESKTOP"
  become: true
  become_method: sudo
  tags:
    - post_install
    - post_gnome_packages
    - post_gnome

- import_tasks: gnome_extensions.yml
  when: "'GNOME' in ansible_env.XDG_CURRENT_DESKTOP"
  tags:
    - post_install
    - post_gnome_extensions
    - post_gnome

- import_tasks: gnome_conf.yml
  when: "'GNOME' in ansible_env.XDG_CURRENT_DESKTOP"
  tags:
    - post_install
    - post_gnome_conf
    - post_gnome

- name: "Check if dropbox is synchronized"
  shell: dropbox status
  register: dropbox_response
  tags:
    - post_install
    - post_docker
    - post_crontab
    - post_environment
    - post_git

- import_tasks: docker.yml
  when: dropbox_response.stdout == "Actualizado"
  tags:
    - post_install
    - post_docker

- import_tasks: crontab.yml
  when: dropbox_response.stdout == "Actualizado"
  tags:
    - post_install
    - post_crontab

- import_tasks: environment.yml
  when: dropbox_response.stdout == "Actualizado"
  tags:
    - post_install
    - post_environment
    - post_git

- import_tasks: git.yml
  when: dropbox_response.stdout == "Actualizado"
  tags:
    - post_install
    - post_git

- import_tasks: sublime.yml
  when: dropbox_response.stdout == "Actualizado"
  tags:
    - post_install
    - post_sublime

- import_tasks: vpn.yml
  become: true
  become_method: sudo
  tags:
    - post_install
    - post_vpn
