---

- name: "Check if dropbox is synchronized"
  shell: dropbox status
  register: dropbox_response
  tags:
    - post_install
    - post_docker
    - post_crontab
    - post_environment
    - post_git

- import_tasks: docker.yml
  when: dropbox_response.stdout == "Actualizado"
  tags:
    - post_install
    - post_docker

- import_tasks: crontab.yml
  when: dropbox_response.stdout == "Actualizado"
  tags:
    - post_install
    - post_crontab

- import_tasks: environment.yml
  when: dropbox_response.stdout == "Actualizado"
  tags:
    - post_install
    - post_environment
    - post_git

- import_tasks: git.yml
  when: dropbox_response.stdout == "Actualizado"
  tags:
    - post_install
    - post_git

- import_tasks: openvpn.yml
  become: true
  become_method: sudo
  tags:
    - post_install
    - post_openvpn
