---

- name: "Copy vpn configuration files to NetworkManager"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
    owner: root
    group: root
  loop:
    - src: bbva_vpn.j2
      dest: /etc/NetworkManager/system-connections/BBVA.nmconnection
    - src: datio_mx_vpn.j2
      dest: /etc/NetworkManager/system-connections/Datio_MX.nmconnection
