---

aur_url: https://aur.archlinux.org

atom_repo: "{{ aur_url }}/atom-editor-bin.git"
dropbox_repo: "{{ aur_url }}/dropbox.git"
chrome_repo: "{{ aur_url }}/google-chrome.git"
code_repo: "{{ aur_url }}/visual-studio-code-bin.git"
skype_repo: "{{ aur_url }}/skypeforlinux-stable-bin.git"
ohmyzsh_repo: "{{ aur_url }}/oh-my-zsh-git.git"
cherrytree_repo: "{{ aur_url }}/cherrytree.git"
postman_repo: "{{ aur_url }}/postman-bin.git"
teamviewer_repo: "{{ aur_url }}/teamviewer.git"
keepass_repo: "{{ aur_url }}/keepassxc-git.git"
buttercup_repo: "{{ aur_url }}/buttercup-desktop.git"
virtualbox_repo: "{{ aur_url }}/virtualbox-bin.git"
tlp_repo: "{{ aur_url }}/tlp-git.git"
telegram_repo: "{{ aur_url }}/telegram-desktop-bin.git"
spotify_repo: "{{ aur_url }}/spotify.git"
slack_repo: "{{ aur_url }}/slack-desktop.git"
rambox_repo: "{{ aur_url }}/rambox-bin.git"
pycharm_repo: "{{ aur_url }}/pycharm-community-eap.git"
yay_repo: "{{ aur_url }}/yay-bin.git"
vagrant_repo: "{{ aur_url }}/vagrant-git.git"
nomachine_repo: "{{ aur_url }}/nomachine.git"
gitkraken_repo: "{{ aur_url }}/gitkraken.git"
sublime_repo: "{{ aur_url }}/sublime-text-nightly.git"
franz_repo: "{{ aur_url }}/franz-bin.git"
forticlient_repo: "{{ aur_url }}/forticlientsslvpn.git"
windscribe_repo: "{{ aur_url }}/windscribe-cli.git"
apachedirectory_repo: "{{ aur_url }}/apachedirectorystudio.git"
java_repo: "{{ aur_url }}/java-openjdk-bin.git"
docker_repo: "{{ aur_url }}/docker-bin.git"
dockercompose_repo: "{{ aur_url }}/docker-compose-bin.git"
megacmd_repo: "{{ aur_url }}/megacmd-bin.git"
megasync_repo: "{{ aur_url }}/megasync.git"
vivaldi_repo: "{{ aur_url }}/vivaldi.git"
brave_repo: "{{ aur_url }}/brave-bin.git"
bitwarden_repo: "{{ aur_url }}/bitwarden-bin"
woeusb_repo: "{{ aur_url }}/woeusb.git"

atom_package: atom-editor-bin
dropbox_package: dropbox
chrome_package: google-chrome
code_package: visual-studio-code-bin
skype_package: skypeforlinux-stable-bin
ohmyzsh_package: oh-my-zsh-git
cherrytree_package: cherrytree
postman_package: postman-bin
teamviewer_package: teamviewer
keepass_package: keepassxc-git
buttercup_package: buttercup-desktop
virtualbox_package: virtualbox-bin
tlp_package: tlp-git
telegram_package: telegram-desktop
spotify_package: spotify
slack_package: slack-desktop
rambox_package: rambox-bin
pycharm_package: pycharm-community-eap
yay_package: yay-bin
vagrant_package: vagrant-git
nomachine_package: nomachine
gitkraken_package: gitkraken
sublime_package: sublime-text-nightly
franz_package: franz-bin
forticlient_package: forticlientsslvpn
deluge_package: deluge-git
windscribe_package: windscribe-cli
apachedirectory_package: apachedirectorystudio
java_package: java-openjdk-bin
docker_package: docker-bin
dockercompose_package: docker-compose-bin
megacmd_package: megacmd-bin
megasync_package: megasync
vivaldi_package: vivaldi
brave_package: brave-bin
bitwarden_package: bitwarden-bin
woeusb_package: woeusb

protonvpn_dependencies:
  - openvpn
  - dialog
  - python-pip
  - python-setuptools

file_manager_plugin: "{{ lookup('template', 'megasync.j2') | replace('\n', '') }}"
