---

aur_url: https://aur.archlinux.org

atom_repo: "{{ aur_url }}/atom-editor-bin.git"
dropbox_repo: "{{ aur_url }}/dropbox.git"
chrome_repo: "{{ aur_url }}/google-chrome.git"
code_repo: "{{ aur_url }}/visual-studio-code-bin.git"
skype_repo: "{{ aur_url }}/skypeforlinux-stable-bin.git"
ohmyzsh_repo: "{{ aur_url }}/oh-my-zsh-git.git"
cherrytree_repo: "{{ aur_url }}/cherrytree.git"
postman_repo: "{{ aur_url }}/postman-bin.git"
teamviewer_repo: "{{ aur_url }}/teamviewer.git"
keepass_repo: "{{ aur_url }}/keepassxc-git.git"
buttercup_repo: "{{ aur_url }}/buttercup-desktop.git"
virtualbox_repo: "{{ aur_url }}/virtualbox-bin.git"
tlp_repo: "{{ aur_url }}/tlp-git.git"
telegram_repo: "{{ aur_url }}/telegram-desktop-bin.git"
spotify_repo: "{{ aur_url }}/spotify.git"
slack_repo: "{{ aur_url }}/slack-desktop.git"
rambox_repo: "{{ aur_url }}/rambox-bin.git"
pycharm_repo: "{{ aur_url }}/pycharm-community-eap.git"
yay_repo: "{{ aur_url }}/yay-bin.git"

atom_package: atom-editor-bin
dropbox_package: dropbox
chrome_package: google-chrome
code_package: visual-studio-code-bin
skype_package: skypeforlinux-stable-bin
ohmyzsh_package: oh-my-zsh-git
cherrytree_package: cherrytree
postman_package: postman-bin
teamviewer_package: teamviewer
keepass_package: keepassxc-git
buttercup_package: buttercup-desktop
virtualbox_package: virtualbox-bin
tlp_package: tlp-git
telegram_package: telegram-desktop
spotify_package: spotify
slack_package: slack-desktop
rambox_package: rambox-bin
pycharm_package: pycharm-community-eap
yay_package: yay-bin
