---

chrome_package: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
chromium_package: chromium
dropbox_package: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb"
gitkraken_package: "https://release.axocdn.com/linux/gitkraken-amd64.deb"
teamviewer_package: "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"
vagrant_package: vagrant
virtualbox_packages:
  - virtualbox-6.0
megacmd_package: "https://mega.nz/linux/MEGAsync/{{ ansible_distribution }}_{{ ansible_distribution_version }}.0/amd64/megacmd-{{ ansible_distribution }}_{{ ansible_distribution_version }}.0_amd64.deb"
megacmd_dependencies:
  - libmediainfo0v5
  - libpcrecpp0v5
  - libzen0v5
  - libcrypto++6
  - libmms0
  - libtinyxml2-6

megasync_package: "https://mega.nz/linux/MEGAsync/{{ ansible_distribution }}_{{ ansible_distribution_version }}.0/amd64/megasync-{{ ansible_distribution }}_{{ ansible_distribution_version }}.0_amd64.deb"
file_manager_plugin: "{{ lookup('template', 'megasync.j2') | replace('\n', '') }}"
