---

chrome_package: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
chromium_package: chromium
dropbox_package: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb"
gitkraken_package: "https://release.axocdn.com/linux/gitkraken-amd64.deb"
teamviewer_package: "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"
vagrant_package: vagrant
