---

install_docker: true
install_dropbox: true
install_code: true
install_spotify: true
install_ohmyzsh: false
install_sublime: false
install_atom: false
install_gitkraken: true
install_telegram: true
install_slack: false
install_forticlientvpn: false
install_tlp: false
install_virtualbox: true
install_pycharm: false
install_keepass: false
install_buttercup: false
install_windscribe: false
install_chrome: true
install_teamviewer: true
install_nomachine: false
install_ecs: false
install_postman: false
install_skype: false
install_java: false
install_apachedirectory: false
install_rambox: false
install_franz: false
install_chromium: false
install_deluge: false
install_cherrytree: false
install_kubectl: true
install_flatpak: false
install_megacmd: true
install_megasync: false
install_vivaldi: false
install_brave: false
install_bitwarden: true
install_lexnet: false
install_pass: false
install_bucklespring: false
install_protonvpn: true
install_prezto: true
install_etcher: true
install_woeusb: true
install_go: true
install_fzf: true
install_vimplugins: true
install_authy: false
install_yakyak: true
install_hiri: false
install_steam: false
install_wireguard: true
install_lens: true
install_typora: true
