---

- name: "[UBUNTU] Copy repository file"
  copy:
    src: ansible.list
    dest: /etc/apt/sources.list.d/ansible.list
    owner: root
    group: root
    mode: 0644

- name: "[UBUNTU] Import Ansible repository key"
  apt_key:
    url: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367
    state: present

- name: "[UBUNTU] Update ansible"
  apt:
    name:
      - ansible
      - python-apt
    update_cache: true
    state: latest
