---

- name: "[FEDORA] Install common packages"
  yum:
    name: "{{ common_packages | list }}"
    state: present
    update_cache: true

- name: "[FEDORA] Install Fedora packages"
  yum:
    name: "{{ fedora_packages | list }}"
    state: present
    update_cache: true
