---

- import_tasks: update_packages.yml
  tags:
    - common
    - update_packages
    - install_packages
    - ansible
    - python
    - python3

- import_tasks: selinux.yml
  when: ansible_distribution == "Fedora"
  tags:
    - common
    - disable_selinux

- import_tasks: install_packages.yml
  tags:
    - common
    - install_packages

- import_tasks: ansible.yml
  tags:
    - common
    - ansible

- import_tasks: python.yml
  tags:
    - common
    - python
    - python3
