---

- name: "[FEDORA] Install Python3"
  yum:
    name:
      - python3
      - python3-pip
      - python3-virtualenv
      - ipython3
      - python3-virtualenvwrapper
    state: latest
    update_cache: true
  when: ansible_distribution == "Fedora"

- name: "[UBUNTU] Install Python3"
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - ipython3
      - virtualenvwrapper
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: "Alternative link for python"
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name: "Alternative link for pip"
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3

- name: "Install python modules"
  pip:
    name:
      - telepot
      - matplotlib
      - numpy
      - beautifulsoup4
      - bs4
      - openstacksdk
      - molecule
      - dnspython
      - docker-py
