---

- name: "[UBUNTU] Upgrade all packages to the latest version"
  apt:
    name: "*"
    state: latest
    update_cache: true
    force_apt_get: true
  when: linux_distribution == "ubuntu"

- name: "[FEDORA] upgrade all packages to the latest version"
  yum:
    name: '*'
    state: latest
    update_cache: true
  when: linux_distribution == "fedora"
