---

- import_playbook: playbooks/load_distro_vars.yml
  tags:
    - always

- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  vars:
    disable_updates: "{{ lookup('env', 'REPO_DISABLE_UPDATES') | default(false) | bool }}"
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
    install_dropbox: false
    install_spotify: false
    install_ohmyzsh: false
    install_sublime: false
    install_atom: false
    install_gitkraken: false
    install_telegram: false
    install_tlp: false
    install_virtualbox: false
    install_pycharm: false
    install_buttercup: false
    install_windscribe: false
    install_teamviewer: false
    install_nomachine: false
    install_skype: false
    install_rambox: false
    install_franz: false
    install_chromium: false
    install_deluge: false
    install_cherrytree: false
    install_kubectl: false
    install_megacmd: false
    install_megasync: false
    install_vivaldi: false
    install_brave: false
    install_bitwarden: false
    install_pass: false
    install_protonvpn: false
    install_prezto: false
    install_etcher: false
    install_woeusb: false
    install_fzf: false
    install_authy: false
    install_steam: false
    install_wireguard: false
    install_lens: false
    install_typora: false
  roles:
    - common
    - extra_software


- hosts: localhost
  connection: local
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
    post_user: "datio"
  pre_tasks:
    - block:
        - name: Create A Password
          pause:
            prompt: "What is your BBVA username?:"
            echo: no
          register: bbva_user

        - name: "Configure BBVA user"
          lineinfile:
            path: "{{ ansible_user_dir }}/.bashrc"
            line: 'export XEUSER={{ bbva_user.user_input }}'
            state: present
      tags:
        - post_install
        - post_env
        - post_environment
  roles:
    - "post_install/{{ post_user }}"
