---

- hosts: localhost
  connection: local
  tasks:
    - assert:
        that:
          - secret is defined
        fail_msg: "'secret' variable must be defined using '-e secret=xxxxx'"

    - name: "find variables files"
      find:
        paths: "."
        patterns: "^.*(?:\\/defaults|\\/vars).*(yml)$"
        use_regex: true
        recurse: true
      register: find_response

    - debug:
        msg: "{{ item }}"
      vars:
        id_query: "[].path"
      loop: "{{ find_response.files | json_query(id_query) }}"

    - include_vars: "{{ item }}"
      vars:
        id_query: "[].path"
      loop: "{{ find_response.files | json_query(id_query) }}"

    - name: "Get the value of variable '{{ secret }}'"
      debug:
        msg: "{{ secret }}"
