---

- import_playbook: playbooks/load_distro_vars.yml

- hosts: localhost
  connection: local
  tasks:
    - block:
        - name: "check if prepare flag exists"
          stat:
            path: /var/tmp/.prepare
          register: flag_response

        - fail:
            msg: "Por favor, antes de continuar ejecuta el comando 'ansible-playbook playbooks/prepare.yml'"
          when: not flag_response.stat.exists
      when: linux_distribution in ["debian", "ubuntu"]
      tags:
        - always


- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  vars:
    disable_updates: "{{ lookup('env', 'REPO_DISABLE_UPDATES') | default(false) | bool }}"
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
  roles:
    - common
    - extra_software


- hosts: localhost
  connection: local
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
    post_user: "{{ post_install_user | default(ansible_user) }}"
  tasks:
    - include_role:
        name: "post_install/{{ post_user }}"
