---

- hosts: localhost
  connection: local
  tasks:
    - import_tasks: load_distro_vars.yml
      tags:
        - always

- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
  roles:
    - common
    - extra_software

- hosts: localhost
  connection: local
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
    post_user: "{{ post_install_user | default(ansible_user) }}"
  tasks:
    - name: "Check if there is any config for {{ post_user }}"
      stat:
        path: "post_install/{{ post_user }}"
      register: stat_response

    - name: "Continue with post install if exists configuration for {{ post_user}}"
      block:
        - name: "[FEDORA] upgrade all packages to the latest version"
          yum:
            name: '*'
            state: latest
            update_cache: true
          when: linux_distribution == "fedora"

        - name: "[UBUNTU] Upgrade all packages to the latest version"
          apt:
            name: "*"
            state: latest
            update_cache: true
            force_apt_get: true
          when: linux_distribution == "ubuntu"

        - name: "[ARCH] upgrade all packages to the latest version"
          pacman:
            update_cache: yes
            upgrade: yes
          ignore_errors: true
          when: linux_distribution == "arch"

        - import_role:
            name: "post_install/{{ post_install_user }}"
      when: stat_response.stat.exists
