---

- import_playbook: playbooks/load_distro_vars.yml
  tags:
    - always

- hosts: localhost
  connection: local
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
    post_user: "{{ post_install_user | default(ansible_user) }}"
  roles:
    - "post_install/{{ post_user }}"
