---

- name: "[LOAD VARS] setting ansible variables"
  import_playbook: playbooks/load_distro_vars.yml
  tags:
    - always

- hosts: localhost
  connection: local
  tasks:
    - name: "check if system is prepared"
      block:
        - name: "check if prepare flag exists"
          stat:
            path: /var/tmp/.prepare
          register: flag_response

        - name: "Exit if system is not prepared"
          fail:
            msg: "Por favor, antes de continuar ejecuta el comando 'ansible-playbook playbooks/prepare.yml'"
          when: not flag_response.stat.exists
      when: linux_distribution in ["debian", "ubuntu"]
      tags:
        - always

####################
# POST INSTALACION #
####################

- hosts: localhost
  connection: local
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ lookup('env', 'USER') }}"
    post_user: "{{ post_install_user | default(ansible_user) }}"
  tasks:
    - name: "[POST INSTALL] user customization"
      include_role:
        name: "post_install/{{ post_user }}"
      tags:
        - always
