---

- hosts: all
  tasks:
    - import_tasks: load_distro_vars.yml
      tags:
        - always

- hosts: all
  become: true
  become_method: sudo
  vars:
    disable_updates: "{{ lookup('env', 'REPO_DISABLE_UPDATES') | default(false) | bool }}"
    install_dropbox: false
    install_spotify: false
    install_ohmyzsh: false
    install_sublime: false
    install_atom: false
    install_gitkraken: false
    install_telegram: false
    install_tlp: false
    install_virtualbox: false
    install_pycharm: false
    install_buttercup: false
    install_windscribe: false
    install_teamviewer: false
    install_nomachine: false
    install_skype: false
    install_rambox: false
    install_franz: false
    install_chromium: false
    install_deluge: false
    install_cherrytree: false
    install_kubectl: false
    install_megacmd: false
    install_megasync: false
    install_vivaldi: false
    install_brave: false
    install_bitwarden: false
  roles:
    - common
    - extra_software

- hosts: all
  vars_prompt:
    - name: bbva_user
      prompt: "What is your BBVA username?"
      private: no
  tasks:
    - block:
        - name: "Configure BBVA user"
          lineinfile:
            path: "{{ ansible_user_dir }}/.bashrc"
            line: 'export XEUSER={{ bbva_user }}'
            state: present
      tags:
        - post_install
        - post_env
        - post_environment

- hosts: all
  vars:
    post_user: "datio"
  roles:
    - "post_install/{{ post_user }}"
