---

- hosts: all
  tasks:
    - import_tasks: load_distro_vars.yml
      tags:
        - always

- hosts: all
  become: true
  become_user: root
  vars:
    disable_updates: "{{ lookup('env', 'REPO_DISABLE_UPDATES') | default(false) | bool }}"
  roles:
    - common
    - extra_software
