---

- hosts: localhost
  connection: local
  tasks:
    - import_tasks: load_distro_vars.yml
      tags:
        - always

- hosts: all
  tasks:
    - import_tasks: load_distro_vars.yml
      tags:
        - always

- hosts: all
  become: true
  become_user: root
  tasks:
    - name: "[FEDORA] upgrade all packages to the latest version"
      yum:
        name: '*'
        state: present
        update_cache: true
      when: linux_distribution == "fedora"

    - name: "[UBUNTU] Upgrade all packages to the latest version"
      vars:
        distros:
          - ubuntu
          - debian
      apt:
        name: "*"
        state: present
        update_cache: true
        force_apt_get: true
      when: linux_distribution in distros

    - name: "[ARCH] upgrade all packages to the latest version"
      pacman:
        update_cache: yes
        upgrade: yes
      ignore_errors: true
      when: linux_distribution == "arch"

    - name: "Create {{ last_update_file }}"
      vars:
        last_update_file: "/var/tmp/.update"
      file:
        path: "{{ last_update_file }}"
        state: touch
