---

- name: "[ARCH] Install virtualbox"
  become: false
  yay:
    name: "{{ virtualbox_package }}"
    state: present
    update_cache: true

- name: "[ARCH] Install vagrant"
  pacman:
    name: vagrant
    state: present
    update_cache: true
  tags:
    - vagrant
