---

- name: "[VSCODIUM] install for {{ linux_distribution }}"
  include_tasks: "codium_{{ linux_distribution }}.yml"

- name: "[VSCODIUM] install extensions"
  block:
    - name: "[VSCODIUM] get json with extensions"
      uri:
        url: "{{ code_extensions_url }}"
      register: extensions_response

    - name: "[VSCODIUM] Install extensions for Visual Studio Codium"
      become: false
      become_user: "{{ ansible_user }}"
      vars:
        id_query: "[].metadata.publisherId"
      command: "codium --install-extension {{ item }}"
      loop: "{{ extensions_response.json | default([]) | json_query(id_query) | list }}"
      ignore_errors: true
  tags:
    - codium_extensions

- name: "[CODIUM] restore settings.json"
  block:
    - name: "[CODIUM] get settings.json"
      uri:
        url: "{{ code_settings_url }}"
      register: settings_response

    - name: "[CODIUM] save settings to file"
      vars:
        gist:
          sync.gist: ""
        project_manager:
          projectManager.git.baseFolders:
            - "{{ ansible_user_dir }}/git"
      copy:
        content: "{{ settings_response.json | combine(gist, recursive=true) | combine(project_manager, recursive=true) }}"
        dest: "{{ ansible_user_dir }}/.config/VSCodium/User/settings.json"
        backup: true
        mode: 0664
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
  tags:
    - codium_settings
