---

- name: "[TELEGRAM] [UBUNTU] install telegram repository"
  apt_repository:
    repo: ppa:atareao/telegram
    state: present

- name: "[TELEGRAM] [UBUNTU] Install Telegram using repository"
  apt:
    name:
      - telegram
    state: present
    update_cache: true
