---

- name: "[FEDORA] Check if ansible_version >= 2.8"
  assert:
    that:
      - ansible_version.full >= "2.6"
    fail_msg: "Ansible version must be >= 2.6. Please, ejecute 'ansible-playbook update_ansible.yml '"
    success_msg: "OK, your ansible version is {{ ansible_version.full }}"

- name: "[FEDORA] Install the skype flatpak"
  flatpak:
    name:  "{{ skype_flatpak }}"
    state: present
