---

- name: "[FEDORA] check if {{ typora_dir }} exits"
  stat:
    path: "{{ typora_dir }}"
  register: typora_response

- name: "[FEDORA] delete {{ typora_dir }} if exits"
  file:
    path: "{{ typora_dir }}"
    state: absent
  when: typora_response.stat.exists

- name: "[FEDORA] create {{ typora_dir }}"
  file:
    path: "{{ typora_dir }}"
    state: directory

- name: "[FEDORA] uncompress typora"
  unarchive:
    src: "{{ typora_package }}"
    dest: "{{ typora_dir }}"
    remote_src: true
    extra_opts:
      - "--strip-components=2"

- name: "[FEDORA] copy typora icon fie"
  copy:
    src: typora_icon.png
    dest: "{{ typora_dir }}"
