---

- name: "[DEBIAN] install megasync package"
  apt:
    deb: "{{ megasync_package }}"
    state: present
    update_cache: true

- set_fact:
    file_manager_plugin: "https://mega.nz/linux/MEGAsync/{{ ansible_distribution }}_{{ ansible_distribution_version }}.0/amd64/nemo-megasync-{{ ansible_distribution }}_{{ ansible_distribution_version }}.0_amd64.deb"
  when: ansible_distribution == "Linux Mint"

- set_fact:
    file_manager_plugin: "https://mega.nz/linux/MEGAsync/{{ ansible_distribution }}_{{ ansible_distribution_version }}.0/amd64/nautilus-megasync-{{ ansible_distribution }}_{{ ansible_distribution_version }}.0_amd64.deb"
  when: desktop_environment == "gnome"

- set_fact:
    file_manager_plugin: "https://mega.nz/linux/MEGAsync/{{ ansible_distribution }}_{{ ansible_distribution_version }}.0/amd64/dolphin-megasync-{{ ansible_distribution }}_{{ ansible_distribution_version }}.0_amd64.deb"
  when: desktop_environment == "kde"

- name: "[DEBIAN] Install megasync for file manager"
  apt:
    deb: "{{ file_manager_plugin }}"
    state: present
  when: file_manager_plugin is defined
