---

- name: "[VSCODE] [FEDORA] Copy repository file"
  copy:
    src: code.repo
    dest: /etc/yum.repos.d/code.repo
    owner: root
    group: root
    mode: 0644
  tags:
    - vscode_repo

- name: "[VSCODE] [FEDORA] Import Microsoft key"
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: "[VSCODE] [FEDORA] check updates]"
  shell: yum check-update
  register: yum_result
  failed_when: yum_result.rc != 100

- name: "[VSCODE] [FEDORA] Install Code"
  yum:
    name: code
    state: present
    update_cache: true
