---

- name: "[VSCODE] [DEB] Copy repository file"
  copy:
    src: code.list
    dest: /etc/apt/sources.list.d/vscode.list
    mode: 0644
    owner: root
    group: root

- name: "[VSCODE] [DEB] Import repository key"
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: "[VSCODE] [DEB] Install code package"
  apt:
    name:
      - libx11-xcb-dev
      - libasound2
      - code
    state: present
    update_cache: true
